### ISSUE TITLE
Spell mistake in whitelist

### ISSUE THREAD

**Issue by coding-sunshine** [codestudiollc/laravel-totem#108]
It's an easy one.
On Tetem.php 'whitelist' is spelled as 'whiltelist'
I tried to create a pull request but got confused on which branch to keep pull request, 2.0 or 3.0

**Comment by roshangautam** [comment]
Looks perfectly fine to me on both 2.0 and 3.0

https://github.com/codestudiohq/laravel-totem/blob/2.0/config/totem.php

https://github.com/codestudiohq/laravel-totem/blob/3.0/config/totem.php

:)

**Comment by coding-sunshine** [comment]
Sorry for not mentioning exact file paths

Actually on the following files
https://github.com/codestudiohq/laravel-totem/blob/3.0/src/Totem.php
https://github.com/codestudiohq/laravel-totem/blob/2.0/src/Totem.php

Both files are having it.

**Comment by roshangautam** [comment]
Fixed in latest releases.

**Comment by coding-sunshine** [comment]
thanks
