### ISSUE TITLE
Not installing in laravel 5.4 version

### ISSUE THREAD

**Issue by mukeshphpdev** [codestudiollc/laravel-totem#110]
![capture](https://user-images.githubusercontent.com/38874869/44398816-eb6d7f80-a562-11e8-8fdc-278922a296b3.PNG)

**Comment by qschmick** [comment]
Which version did you try and install?

**Comment by mukeshphpdev** [comment]
5.4.36

**Comment by qschmick** [comment]
@mukeshphpdev Sorry, I meant which version of Totem are you trying to install? v2 requires Laravel 5.5+ and v3 requires Laravel 5.6+

Additionally, Laravel 5.4 hasn't gotten updates from 8+ months and we are not actively supporting the old v1 version of totem.

**Comment by roshangautam** [comment]
try `composer require studio/laravel-totem:1.*` for 5.4
