### ISSUE TITLE
[BUG] Schedule page and console list desync

### ISSUE THREAD

**Issue by chssmith** [codestudiollc/laravel-totem#115]
In our environment, none of our tasks are getting executed anymore.  On the page, we have tasks (just a sample of our tasks):

![image](https://user-images.githubusercontent.com/25271891/44988035-4c2f8b80-af57-11e8-9ecc-8dc4dd6c8328.png)

But notice that the only task that appears to be executing anymore is the Download TV Guide.  Which was one of the first tasks added to the system.  Most of our tasks look exactly the same: 8/31 was their last execution.  Even though they have upcoming scheduled times.  This includes tasks that are supposed to run every minute.

However, the console command:
![image](https://user-images.githubusercontent.com/25271891/44988171-c233f280-af57-11e8-8387-07cf2115dfb0.png)

Lists nothing.

This morning, I ran a composer update to see if it would fix the problem, and no issues with the update.  But tasks still aren't running.  I checked my crontab:

`* * * * * * php /var/www/html/scheduler/artisan schedule:run >> /var/www/html/scheduler/storage/logs/schedule_runs.log 2>&1`

Which writes to a log file so we can make sure everything is running.  And the scheduled task runs.

Any of the tasks on the page can be run manually by hitting the play button.

**Comment by roshangautam** [comment]
try `php artisan cache:clear` and see what happens

**Comment by chssmith** [comment]
Does not seem to have helped.

![image](https://user-images.githubusercontent.com/25271891/44994643-83109c00-af6d-11e8-9289-1a23eb4a4998.png)

**Comment by roshangautam** [comment]
What version of Laravel and Totem are you running?

**Comment by chssmith** [comment]
Laravel 5.5.43
Totem 2.4.1

**Comment by roshangautam** [comment]
I am not able to reproduce this on Laravel 5.5.42 and Totem 2.4.1. Just tested this on a fresh 5.5 install and its working fine.

Also I can't find Laravel 5.5.43 assuming you are talking about laravel/framework package. The latest tag is 5.5.42

Can you try scheduling a command directly from app/Console/kernel.php and see if that shows up in schedule:list?

**Comment by chssmith** [comment]
See attachment below as far as version numbers.

It does appear scheduling via Kernel.php is working correctly:
![image](https://user-images.githubusercontent.com/25271891/44995898-287a3e80-af73-11e8-904d-8ed7f325bf64.png)
![image](https://user-images.githubusercontent.com/25271891/44995847-efda6500-af72-11e8-96e0-ef5e54701227.png)

And we've been running Totem for about 6 months up to this point.  And nothing changed on Friday when everything seemed to stop running.

Attachment:
![image](https://user-images.githubusercontent.com/25271891/44995762-9bcf8080-af72-11e8-838b-58835aa93260.png)

**Comment by roshangautam** [comment]
I see 5.5.43 now. Still not able to reproduce. The only reason a scheduled task wouldn't show up in schedule:list is if its disabled.

**Comment by chssmith** [comment]
I do have 3 disabled tasks.  But even the task that is running (Download TV Schedule) doesn't show up in that schedule list.  So I'm not certain if it's going to run tomorrow.

In addition, creating new tasks via the totem pages does not appear to add anything into the scheduled tasks list.

**Comment by syphernl** [comment]
Seems like the cache may be an issue here. At least, it is on our end. `schedule:list` doesn't show new entries we added trough the model and still shows the old ones. 

The overview changes once we clear the cache manually. I see that some Totem caching functionality was added at the beginning of September.

**Comment by michalper** [comment]
Hi,

I've exactly the same problem. 
- PHP 7.3.7
- Laravel 5.8.29
- Laravel Totem 5.0.4 

Kernel.php class:
![image](https://user-images.githubusercontent.com/6458084/61632382-01148900-ac8d-11e9-978f-9fea2bc6ca8d.png)

Totem dashboard:
![image](https://user-images.githubusercontent.com/6458084/61632474-37520880-ac8d-11e9-8341-b6dbf2cabe52.png)

Schedule list:
![image](https://user-images.githubusercontent.com/6458084/61632513-56e93100-ac8d-11e9-84a8-c68050ca5800.png)

I don't know what to do next. This is a fresh installation of Totem in very old Laravel project which was updated from version 4.2 to latest 5.8. Project was also migrated from PHP 5.6 to 7.3. After three days of looking for solution, I write to You guys.

Maybe I've missed something when I was migrating Laravel between versions, but seriously I don't know what am I looking for to fix it...

 Please help!

**Comment by b-roberts** [comment]
I had this issue and it was related to how the ConsoleServiceProvider was getting loaded, or rather not getting loaded. The check that is in place to ensure the database is setup doesn't handle non-standard configurations well. 
See https://github.com/codestudiohq/laravel-totem/pull/198
