### ISSUE TITLE
Incompatible with Laravel 5.7.12 and totem table prefix

### ISSUE THREAD

**Issue by marcoocram** [codestudiollc/laravel-totem#122]
We can't use laravel totem with this version of laravel and table prefix.

It fail when tries to do an operation with tasks tables because tries to concatenate several times the table prefix.

Can you check this issue? Thanks!

**Comment by marcoocram** [comment]
i've checked this PR: https://github.com/laravel/framework/pull/26085/files

and it set table on new instance function so it concatenate the prefix

**Comment by roshangautam** [comment]
is this still a problem? Did that PR on laravel/framework fixed it or introduced this issue?

**Comment by marcoocram** [comment]
introduced the issue, now is not working porpertly, im not using the prefix to avoid this problem
