### ISSUE TITLE
[UNKNOWN] Result is not showing

### ISSUE THREAD

**Issue by prakhargvp** [codestudiollc/laravel-totem#125]
Command is Executing but not storing any output.
when upgrading laravel from laravel 5.5 to laravel 5.7
'
![screenshot from 2018-11-15 21-37-56](https://user-images.githubusercontent.com/7056772/48565529-c5b40480-e91e-11e8-95aa-e78c0def8be4.png)

**Comment by roshangautam** [comment]
I can't reproduce this. Works fine on a clean install. Any steps to reproduce this would be really helpful to triage this.

**Comment by d3p4n5hu** [comment]
@prakhargvp I do not know the exact way you are using this package, but i had the same problem. If you are overriding the package, like me, then read on.

I was extending the package for custom use case, however, i forgot to also include/modify the Studio\Totem\Events\Executed class. If you take a look into it, you'll find the code where the actual insertion into the results table takes place. After overriding that code also, it worked for me.

**Comment by LeandroVCastro** [comment]
Do you try use it?

return $this->info("hello log");

**Comment by roshangautam** [comment]
@prakhargvp did you get this to work?
