### ISSUE TITLE
Is that really necessary to check 'tasks' table every time?

### ISSUE THREAD

**Issue by chao** [codestudiollc/laravel-totem#127]
Our DB operator noticed there is tons of query on information_schema.tables (`SELECT * FROM information_schema.tables WHERE table_schema=? and table_name='tasks'`) which are caused by laravel-totem.

After digging the code, in the `TotemServiceProvider.php` you check the 'tasks' table existence every time. Is this really necessary?

**Comment by qschmick** [comment]
This check is in place to ensure the service isn't booted if the migration hasn't run yet to create the base table. An issue arose in the past where a new project include totem and had immediate failures as the migrations weren't run. We should be able to wrap that check with some caching to reduce that select overhead.

**Comment by chao** [comment]
Yes, if the table wasn't correctly created, an exception will be thrown in `ConsoleServiceProvider`, right?

Maybe you can just wrap the [following code](https://github.com/codestudiohq/laravel-totem/blob/691fff399d1b2cdceb62aa17938f3d630b173e9b/src/Providers/ConsoleServiceProvider.php#L31) with `try... catch...`:

```PHP
$tasks = app('totem.tasks')->findAllActive();
```

**Comment by qschmick** [comment]
@chao See PR 131
