### ISSUE TITLE
[BUG] Field types not compatible with SQL Server

### ISSUE THREAD

**Issue by Namoshek** [codestudiollc/laravel-totem#128]
After creating the first task, the dashboard stopped working with the error:

> SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Operand data type nvarchar is invalid for avg operator. (SQL: select avg([duration]) as aggregate from [totem_task_results] where [totem_task_results].[task_id] = 1 and [totem_task_results].[task_id] is not null) 

The reason is obviously the field type of `duration` in the `task_results` table:

```php
Schema::create(config('totem.table_prefix').'task_results', function (Blueprint $table) {
    $table->increments('id');
    $table->unsignedInteger('task_id');
    $table->timestamp('ran_at')->useCurrent();
    $table->string('duration');
    $table->longText('result');
    $table->timestamps();
});
```

Is there any particular reason one would want `duration` to be a non-numeric field and still call aggregate functions on it?

_Note: This is most likely an issue that only occurs in combination with Microsoft SQL Server._

**Comment by roshangautam** [comment]
This is very similar to #134

**Comment by qschmick** [comment]
@Namoshek Just opened a PR to update to decimal

**Comment by qschmick** [comment]
Fixed in https://github.com/codestudiohq/laravel-totem/releases/tag/v5.2.0
