### ISSUE TITLE
Disable writing to log

### ISSUE THREAD

**Issue by joaolisboa** [codestudiollc/laravel-totem#129]
According to the config and the code I can't seem to find a way to disable the Log::info calls being made, which is quickly filling up the laravel-logs which is undesirable for big projects. This is just after enabling totem for 30 minutes in our system:

![image](https://user-images.githubusercontent.com/17931192/49879947-fb1b1780-fe22-11e8-8ae6-6fa61b885657.png)

**Comment by gcdsm12** [comment]
Please fix it.

![image](https://user-images.githubusercontent.com/7134503/49938150-ebf2a300-fed0-11e8-80a2-e33f9b0ec3b4.png)

**Comment by qschmick** [comment]
@joaolisboa Can you provide an example of the info output? It's been a bit since I was digging around in Totem but I don't remember anywhere that we directly log info calls. Thanks for any additional info and I'll work on getting it configurable

**Comment by joaolisboa** [comment]
@qschmick Here's an example.

![image](https://user-images.githubusercontent.com/17931192/49943907-ffa60580-fee0-11e8-9573-a7f7262e5b3d.png)

**Comment by qschmick** [comment]
@joaolisboa What is your broadcast driver? `config/broadcasting.php`

**Comment by joaolisboa** [comment]
@qschmick Seems to be Laravel default config which is pointing to the log in the .env. So this would be the cause, right? But I still think it'd be nice to have an option to configure these logs on totem, instead of outright disabling the broadcast log.

![image](https://user-images.githubusercontent.com/17931192/49945281-6842b180-fee4-11e8-8078-805a559a2c78.png)

**Comment by qschmick** [comment]
@joaolisboa We are only using the default broadcast event so you have it configured to go to logs which it is. Are you asking us to have Totem config contain its own broadcast driver prop?

**Comment by joaolisboa** [comment]
@qschmick I'm asking if there's a way to enable/disable the log for Totem without having to change the normal broadcast log as it is configured by default. Because we want to disable these particular logs without disabling the whole broadcast logs.

**Comment by gcdsm12** [comment]
@qschmick please change it,we do not need to consume extra space with logs, allow a setting to disable or enable these logs in general or by cronjob separately.

In only last seven days consume 250MB it's not necessary for us.
![image](https://user-images.githubusercontent.com/7134503/50228953-1943c300-03a1-11e9-8f1f-dd8650477ebd.png)

**Comment by qschmick** [comment]
@gcdsm12 Totem isn't doing anything except using the broadcast driver. Changing this from log to another option will stop those infos

**Comment by qschmick** [comment]
@gcdsm12 @joaolisboa This is the built in framework process of using the specific BROADCAST_DRIVER of `log`. Totem is not doing anything special or custom here to cause these logs. Please use the already existent config option (https://laravel.com/docs/5.7/broadcasting#configuration). If you have a better solution please open a PR and we will review. Thank you for the details and collaboration.

**Comment by joaolisboa** [comment]
@qschmick I understand now this is Laravel standard behavior, The issue is right now I have no way to change broadcast driver. And disabling this driver will disable Totem. So for me to keep this, the log will keep piling up. Is there no other way to configure this?

**Comment by roshangautam** [comment]
I am closing this as you have opened another issue (#132) similar to this one. Looks like you have found a way around it. Feel free to send a PR and we will be more than happy to review it.

**Comment by truffolone** [comment]
May I ask to reopen the issue? I had a similar problem that I was finally able to fix and would like to share since this was one of the first results on a google search, in case someone had the same problem as me

I don't know if that can be you case but I encountered a similar problem using Laravel 5.6

Whet I found out was that the cron for the queued jobs with

    * * * * * cd /path-to-your-project && php artisan schedule:run >> /dev/null 2>&1

I forgot to specify the user processing the cron, so the process was handled by the super user and subsequently locking up files / resources with the wrong permissions

so, I changed the cron command to

    * * * * * apache:apache cd /path-to-your-project && php artisan schedule:run >> /dev/null 2>&1

which fixed my problem. Now I have my logs clear with no failed process attempts

**Comment by joaolisboa** [comment]
Unfortunately(or fortunately since it's not as bad) this is not the issue I have, since these are not errors, just info logs. These logs are part of the broadcast, which in my project is defined as `log`, since at the moment I have no other alternative. 

What happens is every time a cron runs, it seems to go through the broadcast with data relevant to the task to be executed so it gets written to the logs and this fills up pretty quickly in my project(logs are averaging at 30MB per day since using Totem for cron management). 

Everything else is running fine although I've opened an issue related to the way Totem uses the queue(#132) because it seems to be unnecessarily using the queue when it could be all dispatched immediately using the `sync` queue driver(`ShouldBroadcastNow` vs `ShouldBroadcast`).
