### ISSUE TITLE
[REQUEST] Queue driver or name

### ISSUE THREAD

**Issue by joaolisboa** [codestudiollc/laravel-totem#132]
I'm developing a feature for my web app and am wondering if there's any possibility to have an option to make the broadcast event extend `ShouldBroadcastNow` instead of `ShouldBroadcast` so that it uses the `sync` queue driver instead of the one defined in the env? Or at least a config option to define the queue of the events so I can ignore the jobs created by Totem? 

Ideally I'd want to use ShouldBroadcastNow because I want crons do depend on the queue workers. The idea for me here is to not have the jobs and crons mixed together in my web app as I'm working on an interface to manage and analyze jobs, which for crons with Totem is completely unnecessary and clutters the information I need. And I'd like to processes to be distinct from each other.

**Comment by roshangautam** [comment]
Feel free to send a PR. We will be more than happy to review.

**Comment by b-roberts** [comment]
PR: https://github.com/codestudiohq/laravel-totem/pull/200
