### ISSUE TITLE
Typo in service provider

### ISSUE THREAD

**Issue by Insolita** [codestudiollc/laravel-totem#133]
https://github.com/codestudiohq/laravel-totem/blob/cd6a3db56c4ba9a4d37455090c969045e71ce7e4/src/Providers/TotemServiceProvider.php#L67

seems it should be 
```php
define(
  'TOTEM_DATABASE_CONNECTION', 
   config('totem.database_connection') ?? Schema::getConnection()->getName()
);
```
because third parameter of define function must be boolean, and it deprecated in latest php versions, that raise exception

**Comment by roshangautam** [comment]
What version of PHP are you using?

**Comment by Insolita** [comment]
7.3

**Comment by roshangautam** [comment]
Thanks. Does Laravel officially support 7.3 already?

**Comment by Insolita** [comment]
But real reason not in my php version, see define function signature
 http://php.net/manual/ru/function.define.php
you doesn't have errors because third param was recognized as boolean true

**Comment by Insolita** [comment]
I`m only in local enviroment use it with 7.3 as a fact it has some problem with opcache, i disable it
https://github.com/laravel/framework/issues/27052

**Comment by fititnt** [comment]
@Insolita try PHP 7.3.1 stable. xdebug and opcache should be working on.

**Comment by vesper8** [comment]
Also having this issue since upgrading to PHP 7.3

Laravel Valet now defaults to PHP 7.3

In any case, this is clearly a typo. You meant to set the default connection name if one is not provided, define() method does not accept a 3rd parameter for this purpose. 

https://secure.php.net/manual/en/function.define.php
