### ISSUE TITLE
[BUG] Postgres incompatible  query

### ISSUE THREAD

**Issue by Insolita** [codestudiollc/laravel-totem#134]
https://github.com/codestudiohq/laravel-totem/blob/cd6a3db56c4ba9a4d37455090c969045e71ce7e4/src/Task.php#L132

Column 'duration' declared as varchar type.

https://github.com/codestudiohq/laravel-totem/blob/cd6a3db56c4ba9a4d37455090c969045e71ce7e4/database/migrations/2017_08_05_201914_create_task_results_table.php#L21

Postgres can apply avg function only on  columns with type smallint, int, bigint, real, double precision, numeric or interval 

https://postgrespro.ru/docs/postgresql/9.6/functions-aggregate

**Comment by roshangautam** [comment]
This would be the lowest in my priority as I dont use `postgres` for any of my applications. I would really appreciate if you or someone else who has a higher priority to get this to work in `postgres` send a PR to fix this.

**Comment by qschmick** [comment]
@Insolita Just opened a PR to update to decimal

**Comment by qschmick** [comment]
Fixed in https://github.com/codestudiohq/laravel-totem/releases/tag/v5.2.0
