### ISSUE TITLE
[REQUEST] Scheduling Queued Jobs

### ISSUE THREAD

**Issue by Insolita** [codestudiollc/laravel-totem#135]
Have you any plans to add ability to schedule Jobs, not only artisan commands  (At now this leads to writing additional  wrappers ) but laravel give us native ability

**Comment by roshangautam** [comment]
Haven't gotten a lot of time lately to work on totem but this seems interesting. Adding a reference link: https://laravel.com/docs/5.7/scheduling#scheduling-queued-jobs

Also feel free to send a PR, I will be more than happy to review and merge.
