### ISSUE TITLE
[REQUEST] Add autocomplete for field with command choosing 

### ISSUE THREAD

**Issue by Insolita** [codestudiollc/laravel-totem#136]
Add ability for autocomplete like select2 At now, choosing command from long command list  is not comfortable

**Comment by roshangautam** [comment]
How does this look?

![final_5caa7d7b2a4973001380a5ee_534060](https://user-images.githubusercontent.com/978347/55691498-57b2bd00-5953-11e9-8126-ba80033362c7.gif)

**Comment by roshangautam** [comment]
Tagged v5.0.1 which includes this component. Please check
