### ISSUE TITLE
[BUG] refactor caching strategy when performing actions (import / create / delete / export)

### ISSUE THREAD

**Issue by vesper8** [codestudiollc/laravel-totem#139]
I'm confusing as to why this is happening but it seems if you export your tasks as json, then start from a fresh state (After truncating all tables or running php artisan migrate:fresh, and then try to import your tasks.json

It fails with the error
```
No query results for model [Studio\Totem\Task].
```

From a fresh state / fresh install

Visit /totel

Click new, create a new task and add to it a frequency (Every 5 minutes)

Then export that as json

From here, if you click on your one single task, and then delete it. You can see that the 3 task tables are now empty. And the task list is empty. From here if you click import and choose your tasks.json, it does properly import it back

However if you run php artisan migrate:fresh

The 3 tasks tables are still empty, but upon trying to import your tasks.json, you get an error

**Comment by vesper8** [comment]
Upon further debugging, I realize this is a cache issue

after running php artisan migrate:fresh, if you clear the cache with php artisan cache:clear

Then you able to import your tasks.json

What is happening is the import method of EloquentTaskRepository is running 
```
$task = $this->find($data->id);
```

on the data provided by the json file, and it is somehow finding the old task in the cache, even though the database itself is empty at this point. It then attempts to update that record and fails because the record doesn't actually exist

So we have an instance where $this->find queries the cache but $this->update performs an action on the database

This feels inconsistent.. probably when performing this import method we should not be looking at the cache at all, either force the find() command to hit the database, or clear the tasks cache before proceeding with the import

**Comment by vesper8** [comment]
I understand the cache is meant to not constantly query the db every minute when the task scheduler runs. But when performing actions such as add/edit/export/import I think the cache should be ignored/cleared prior to these actions

Perhaps adding a means to clear the cache from the UI would be beneficial as well

**Comment by roshangautam** [comment]
Thanks for spending time on this and sorry about the caching mechanism causing you issues. Can you please re phrase the title to something like "refactor caching strategy" or what ever is more suitable to the root cause of the issue. Also feel free to submit a PR if you have something in your mind to address this

**Comment by vesper8** [comment]
Sure, no problem. I edited the title and I'll see what I can think of.

For sure the big problem leading to issues here is that when you delete a task, it somehow remains in the cache.

**Comment by vesper8** [comment]
this is a confirmed bug.. unless it has been fixed then I don't think stale bot should be closing it
