### ISSUE TITLE
Page isn't refreshing after execute task manually

### ISSUE THREAD

**Issue by LeandroVCastro** [codestudiollc/laravel-totem#140]
The Totem page isn't refreshing automatic when execute a task manually. I'm needing press F5 to reload and see new logs...

Anybody else with the same problem?

**Comment by roshangautam** [comment]
This is by design. Currently real time refresh is not implemented. Closing this to honor #137

**Comment by LeandroVCastro** [comment]
Do you could explain the reason for it, please?
