### ISSUE TITLE
[Proposal] When a task is executed, the dashboard is updated after execution

### ISSUE THREAD

**Issue by lroggen** [codestudiollc/laravel-totem#149]
Essentially real time data refresh. 

The proposed solution would be to convert the table rows to a Vue component. When the task execute button is clicked, a request is made to run the task. On successful completion of the execute task request, a vue event is fired and the response data from the request (updated to a Task Collection instead of redirect()->back()) is passed to the TableRow vue component and is updated to the user.

**Comment by qschmick** [comment]
@lroggen Sounds good, feel free to open a PR

**Comment by roshangautam** [comment]
This has been merged and released. Thanks @lroggen
