### ISSUE TITLE
[BUG] v5.0.1 empty command list

### ISSUE THREAD

**Issue by jayjfletcher** [codestudiollc/laravel-totem#154]
After pulling the latest tagged release (v5.0.1), I noticed I was no longer able to select a command to schedule:

![Screen Shot 2019-04-09 at 12 32 08 PM](https://user-images.githubusercontent.com/5743488/55817971-99fb0c00-5ac3-11e9-94db-9dd3f47feecc.png)
![Screen Shot 2019-04-09 at 12 32 17 PM](https://user-images.githubusercontent.com/5743488/55817972-99fb0c00-5ac3-11e9-8d62-8ee81377fb4a.png)

It appears to be an issue with the vue component. I'll dig deeper when I get a chance.

**Comment by roshangautam** [comment]
try republishing the assets and see what happens. `php artisan totem:assets`

**Comment by jayjfletcher** [comment]
I have deleted the assets, removed the package, cleared my cache,  and then reinstalled the package and republished the assets. Tried in both Chrome and Firefox, still no luck. Getting the same error.

**Comment by roshangautam** [comment]
Thanks. I will test this on a fresh install as well and let you know my findings.

**Comment by jayjfletcher** [comment]
I found the issue, I'll be submitting a PR

**Comment by roshangautam** [comment]
rofl, just saw your comment while pushing the bug fix

**Comment by jayjfletcher** [comment]
Thanks

**Comment by roshangautam** [comment]
Sure thing. Let me tag a new version real quick.
