### ISSUE TITLE
Class db does not exist

### ISSUE THREAD

**Issue by crissi** [codestudiollc/laravel-totem#156]
composer gives me this error when trying to require the package:
![image](https://user-images.githubusercontent.com/3076578/56042277-fa47b300-5d3a-11e9-8aaf-b0807c9f2a40.png)

**Comment by roshangautam** [comment]
Just tested installing totem in a fresh Laravel installation and everything works fine for me.

Also `db` is a core component of Laravel and your error is originating from Container class. Does your Laravel installation work fine without totem?

**Comment by crissi** [comment]
Yes if I remove totem it works again, I am running the install with —ignore-platform-reqs , I don’t know if that can be a cause

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Roshan Gautam <notifications@github.com>
Sendt: Friday, April 12, 2019 5:46:40 PM
Til: codestudiohq/laravel-totem
Cc: Christian; Author
Emne: Re: [codestudiohq/laravel-totem] Class db does not exist (#156)


Just tested installing totem in a fresh Laravel installation and everything works fine for me.

Also db is a core component of Laravel and your error is originating from Container class. Does your Laravel installation work fine without totem?

**Comment by roshangautam** [comment]
Can you please try without that option and see what happens?

**Comment by crissi** [comment]
Ok found out where the error happens, TotemServiceProvider.php

![image](https://user-images.githubusercontent.com/3076578/56114429-15940780-5f61-11e9-8588-0c4f34970093.png)

The error happens when calling the Schema::getConnection()

**Comment by roshangautam** [comment]
You shouldn't be running composer install with `—ignore-platform-reqs`. Totem requires a database to function and using that flag means ignoring basic requirements.
