### ISSUE TITLE
After adding tasks issue

### ISSUE THREAD

**Issue by randomparanoia** [codestudiollc/laravel-totem#157]
After adding tasks I get this error on UI:

```
SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'tasks' (SQL: select `tasks`.*, (select `ran_at` from `totem_task_results` where `task_id` = `tasks`.`id` order by `created_at` desc limit 1) as `last_ran_at`, (select avg(duration) from `totem_task_results` where `task_id` = `tasks`.`id`) as `average_runtime` from `totem_tasks` order by `description` asc limit 20 offset 0)
```
Removing table prefix ( undesirable ) fixes it.

I'm using version 5.0.2 upgraded from 5.7 > 5.8 and rerun publish assets. Also removed package an retried. thanks

**Comment by jorgv** [comment]
Have the same issue,

I am not sure if is related to this Parent Model Class
```
    public function getTable()
    {
        if (str_contains(parent::getTable(), TOTEM_TABLE_PREFIX)) {
            return parent::getTable();
        }

        return TOTEM_TABLE_PREFIX.parent::getTable();
    }
```

**Comment by binnicordova** [comment]
if not necessary, really, remove the "totem" from your prefix on .env

**Comment by binnicordova** [comment]
protected $table = TOTEM_TABLE_PREFIX.'tasks';
![image](https://user-images.githubusercontent.com/42467277/57255725-5b049b80-701a-11e9-9f27-0c008763d86f.png)

**Comment by binnicordova** [comment]
mmm na.. the solution is edit the class "Result" and "EloquentTaskRepository"
![image](https://user-images.githubusercontent.com/42467277/57319575-7aef9a00-70c2-11e9-91d7-35a574c05be8.png)
![image](https://user-images.githubusercontent.com/42467277/57319593-86db5c00-70c2-11e9-9864-ceb1eab4c2a4.png)

**Comment by marcoocram** [comment]
when this will be released on a new version?

**Comment by roshangautam** [comment]
Fix has been released now. Please upgrade to v5.0.3

**Comment by marcoocram** [comment]
Thanks!!
