### ISSUE TITLE
Blade Recommendations

### ISSUE THREAD

**Issue by mprythero** [codestudiollc/laravel-totem#159]
I was just more curious than anything, but is it only recommended to use only the blades provided or are there suggested ways for integrating this into our own layouts? Thanks and this looks like a great asset!

**Comment by b-roberts** [comment]
The code is mostly setup for this. You only need to copy the views from this project into your own project and put them in `resources/views/vendor/totem`

See https://github.com/codestudiohq/laravel-totem/pull/199 to add a hook into the artisan command `php artisan vendor:publish` to do just this
