### ISSUE TITLE
[PROPOSAL] Fix broken TOTEM_TABLE_PREFIX

### ISSUE THREAD

**Issue by dylanmslavin** [codestudiollc/laravel-totem#163]
The following error is thrown on the `/totem/tasks` page if any tasks exist in the database.

```SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'tasks' (SQL: select `tasks`.*, (select `ran_at` from `totem_task_results` where `task_id` = `tasks`.`id` order by `created_at` desc limit 1) as `last_ran_at`, (select avg(duration) from `totem_task_results` where `task_id` = `tasks`.`id`) as `average_runtime` from `totem_tasks` order by `description` asc limit 20 offset 0)```

A fix is proposed in https://github.com/codestudiohq/laravel-totem/issues/157

This fix should be implemented in order to make the `TOTEM_TABLE_PREFIX` usable again.

**Comment by roshangautam** [comment]
Fix has been released now. Please upgrade to v5.0.3
