### ISSUE TITLE
CLEANUP OPTIONS editing

### ISSUE THREAD

**Issue by bondas83** [codestudiollc/laravel-totem#168]
When editing Auto Cleanup type, library is showin that which is not selected, because of error in CODE

`<input type="radio" name="auto_cleanup_type" value="days" {{old('auto_cleanup_type', $task->auto_cleanup_type) !== 'results' ? '' : 'checked'}}> Days`

it says that if parameter is results then if  go to else and select Days

**Comment by oliworx** [comment]
I can confirm this issue

**Comment by roshangautam** [comment]
@bondas83 can you please send a PR for this fix?

**Comment by qschmick** [comment]
Thanks @bondas83 for the fix in PR #285.
