### ISSUE TITLE
Pusher horizon ant totem in one project failed

### ISSUE THREAD

**Issue by bondas83** [codestudiollc/laravel-totem#169]
if i set BROADCAST_DRIVER to pusher and QUEUE_DRIVER to redis. I got a lot off errors about pusher messages.
And I got all event to horizon, and some of them stuck in jobs
![image](https://user-images.githubusercontent.com/29758515/61222211-e4bf9c00-a722-11e9-9617-d126d86a5a49.png)

**Comment by ManojKiranA** [comment]
can you share some errorlog

**Comment by bondas83** [comment]
I fix this issue with rewriting BroadcastingEvent to this:

`<?php
#disable event to Redis server
namespace Studio\Totem\Events;

class BroadcastingEvent extends TaskEvent
{
}
`

**Comment by qschmick** [comment]
@bondas83 We add an ability to toggle off broadcasting for Totem here https://github.com/codestudiohq/laravel-totem/pull/181
