### ISSUE TITLE
[BUG] Tasks list last run time formatting 12 hour instead of 24.

### ISSUE THREAD

**Issue by chrislarrycarl** [codestudiollc/laravel-totem#171]
Computed `lastRunDate()` [in the TaskRow Vue component](https://github.com/codestudiohq/laravel-totem/blob/5.0/resources/assets/js/tasks/components/TaskRow.vue#L62) is using 12 hour format instead of 24. This results in the tasks list showing a "different" time than the Execution Results list within Task Details (which uses the stored format). 

Changing the moment format string to `HH` should resolve it.

```
lastRunDate() {
    return moment(this.task.last_result.ran_at).format('YYYY-MM-DD HH:mm:ss');
},
```

**Comment by roshangautam** [comment]
If you don't mind, can you please send a PR for this?
