### ISSUE TITLE
schedule task not running 

### ISSUE THREAD

**Issue by ankit-aresourcepool** [codestudiollc/laravel-totem#173]
Hello 
i am working on laravel 5.6  and i am using totem   "studio/laravel-totem": "v3.3.1". the issue is totem task is not firing. i have checked with every minute schedlue task and between but no luck.
and all my kerrnal task is running 

please help me i need this is working urgently
![Screenshot from 2019-07-25 16-17-17](https://user-images.githubusercontent.com/37215290/61868747-bba7c400-aef7-11e9-945d-e889ce78c9b1.png)

**Comment by ManojKiranA** [comment]
have you added the `php artisan schedule:run >> /dev/null 2>&1` inside the cron entry of the server

**Comment by ankit-aresourcepool** [comment]
yes 
the main issue was i need to clear cache than scheduler working.
this was not working on local server but now i have checked it on live and its working.
i have one more query :- in my console command i am hitting third party api and these api with thousand of pages. so my script running continuously many days. so i want these script stop in 9 am morning and again start in 9 pm .
so how can i give option to  stop running script  from admin account

can you please help me
can i do this with totem?
thanks

**Comment by michalper** [comment]
I've got the same problem. Added schedule:run to crontab. But totem cannot find any tasks and returns only:
**php artisan schedule:list
No Scheduled Commands Found**

I've created new project on fresh Laravel 5.8.*

**Comment by ankit-aresourcepool** [comment]
> I've got the same problem. Added schedule:run to crontab. But totem cannot find any tasks and returns only:
> **php artisan schedule:list No Scheduled Commands Found**
> 
> I've created new project on fresh Laravel 5.8.*

i got the solution. please run php artisan cache:clear and after that totem find the task and will work fine

**Comment by michalper** [comment]
@ankit-aresourcepool 

> MacBook-Pro-Peru:totem michalper$ php artisan cache:clear
> **Application cache cleared!**
> MacBook-Pro-Peru:totem michalper$ php artisan schedule:list
> **No Scheduled Commands Found**

My totem list:
![Zrzut ekranu 2019-08-27 o 10 48 49](https://user-images.githubusercontent.com/6458084/63761813-10a57400-c8c2-11e9-886f-e1c53447f7e1.png)

Do I need any special configuration in my .env or config files?

**Comment by michalper** [comment]
@ankit-aresourcepool 

When I defined my own **TOTEM_DATABASE_CONNECTION** in .env php artisan schedule:list didn't read task definitions from database. Totem Web UI worked properly.

But when I used default database connection, then schedule:list found tasks!

Thanks for help :)

**Comment by b-roberts** [comment]
I had this issue and it was related to how the ConsoleServiceProvider was getting loaded, or rather not getting loaded. The check that is in place to ensure the database is setup doesn't handle non-standard configurations well. 
See https://github.com/codestudiohq/laravel-totem/pull/198
