### ISSUE TITLE
Model 中应该不要用 request()->all() processData

### ISSUE THREAD

**Issue by liushoukun** [codestudiollc/laravel-totem#175]
如果我在一个 job 或者 command 中添加 task  那就比较难了  只能依赖 web 和 api ，
把  EloquentTaskRepository.php  改造下   可否？

**Comment by roshangautam** [comment]
I used google translate to understand your question and this is what I got : 

"If I add a task to a job or command, it's harder to rely on the web and api. Transform 
EloquentTaskRepository.php Can you?"

I quite didn't understand the problem and would appreciate if you can help me understand.
