### ISSUE TITLE
php artisan schedule:list cannot read tasks from Totem

### ISSUE THREAD

**Issue by michalper** [codestudiollc/laravel-totem#177]
1. I've created new project on fresh Laravel 5.8.*. 
2. I've added **"studio/laravel-totem": "^5.0"** to composer.json, nothing else. 
3. Then I've created new task to scheduler using Totem form:
![Zrzut ekranu 2019-08-27 o 10 48 49](https://user-images.githubusercontent.com/6458084/63756282-5fe6a700-c8b8-11e9-8ec3-b0c76e2afd6b.png)
4. I've already had schedule:run in crontab:
** totem/artisan schedule:run >> /dev/null 2>&1 **
5. Tasks not firing, because php artisan schedule:list returns only
**No Scheduled Commands Found**

I'm using latest MacOS, PHP 7.3.* and MySql 5.7.*. 
I've already tried to 
- clean cache, 
- optimize, 
- create new Laravel fresh project only for Totem tests, 
- change between different databases,
- create own config/totem.php file with empty configuration.

Nothing helped.

Do I need any special configuration in .env or database.php/cache.php files?

**Comment by michalper** [comment]
When I defined my own **TOTEM_DATABASE_CONNECTION** in .env php artisan schedule:list didn't read task definitions from database. Totem Web UI worked properly.

But when I used default database connection, then schedule:list found tasks!

I think this is a bug.

**Comment by roshangautam** [comment]
Thanks for reporting and debugging. Sorry didn't get a chance to help, am pretty slammed at my day job at the moment. But feel free to submit a PR if you will and I will make sure I review, provide feedback and merge.

**Comment by b-roberts** [comment]
I had this issue and it was related to how the ConsoleServiceProvider was getting loaded, or rather not getting loaded. The check that is in place to ensure the database is setup doesn't handle non-standard configurations well. 
See https://github.com/codestudiohq/laravel-totem/pull/198

**Comment by michalper** [comment]
@roshangautam @b-roberts any progress here?

**Comment by pengan95** [comment]
this problem still exist in laravel 8.*

**Comment by gam5583** [comment]
I have the same problem. Help!

**Comment by mgip** [comment]
i have the same problem

**Comment by klytron** [comment]
having the same problem, using laravel 8.*
