### ISSUE TITLE
[PROPOSAL] Provide Support for SSL/TLS Termination

### ISSUE THREAD

**Issue by blakehooks** [codestudiollc/laravel-totem#179]
Certain web hosts implement SSL and TLS termination technology, where the request shows as https in the browser but is passed around inside the network as an http request. This causes an issue when submitting the "Create Task" form as the url is https://domain.com/totem/tasks/create however the form action is set to http://domain.com/totem/tasks/create which causes the request to be redirected and the form data dropped.

This could be resolved by dropping the action attribute on Line 7 of form.blade.php

**Comment by roshangautam** [comment]
merged
