### ISSUE TITLE
Running out of memory with large task results

### ISSUE THREAD

**Issue by oliworx** [codestudiollc/laravel-totem#188]
I have a task that produces quite a lot of output.
When I want to view/edit the task details, an out-of-memory error occurs:

_Allowed memory size of 134217728 bytes exhausted (tried to allocate 23625728 bytes)_

But the whole table task_results is just 45MB in size.
So there must be some memory issue in this action.

**Comment by qschmick** [comment]
@oliworx When you view a task it loads all of the tasks results. While the table only takes 45MB loading that data into classes takes of more memory. You get determine rough memory usage via tinker and `memory_get_usage`. There will be limitations on our end if you have massive outputs for the commands on what we can do to better display them. I have this used in a project with tasks that have larger outputs and many thousands of results per task and can view/edit without issue.

Which version of Laravel are you running?
Which version of Totem?
Can you increase memory limits?
Can you give an example of the output and it's size?
Are you able to run tinker and see what the memory usage is to load the task you are trying to edit/view?
