### ISSUE TITLE
route:call

### ISSUE THREAD

**Issue by sergionader** [codestudiollc/laravel-totem#192]
Hey, 

I am trying to run it with the comand
`route:call`
and using this as parameter: 
`/api/v1/test?api_key=1234567890`

The response is
`The "/api/v1/test?api_key" argument does not exist.` 
Note that the api_key values is omitted on the error message.

The same command: 
`php artisan route:all /api/v1/test?api_key=1234567890`
runs on the command line. 

What am I missing? 

Thanks,

**Comment by qschmick** [comment]
@sergionader A few quick questions
1) What version of Laravel are you running
2) Which version of Totem do you have installed
3) Is this a custom artisan command and if so can you provide the signature

The issue is with the way we are parsing the arguments provided so we can construct a call to `Artisan::call`. Since you have an `=` in the parameter string we assume that it is an option not an argument so we explode it and pass something like this to `Artisan::call`

```
Artisan::call('route:call',
[
   '/api/v1/test?api_key' => '1234567890' 
]);
```

Artisan is then throwing the error that the command called doesn't have an option in its signature for `/api/v1/test?api_key`.

**Comment by sergionader** [comment]
Hey, @qschmick!

Thanks for your reply. 
1) Laravel Framework 5.8.35
2) "studio/laravel-totem": "^5.2",
3) I am not sure if I understood the question. What signature? 

I may be doing something wrong and perhaps the question should be: 
how do I schedule `/api/v1/test?api_key=1234567890`to run? 

This is what I currently have working on my `app/Console/Kernel.php` file: 
```
$schedule->command('route:call /api/v1/test?api_key=1234567890')->dailyAt('15:30')->environments(['production']);
```

Regards!!!

**Comment by qschmick** [comment]
@sergionader Thanks for the updated info. As for the command, is that a built in command as I'm not seeing it as valid in my repos running Laravel 5.8.35
I get this as output:
```
 Command "route:call" is not defined.  
                                        
  Did you mean one of these?            
      route:cache                       
      route:clear                       
      route:list                        
```

If you created this command, can you post the value of the `protected $signature` within the commands class file.

I've found this reference while looking:
https://gist.github.com/nasirkhan/63320617050f6f8490795e1760ec03cf

From the looks of that it was designed for a much older version of Laravel and the signature/example shows using an option as seen here:

`php artisan route:call --uri=/route/path/with/param`

**Comment by sergionader** [comment]
Hey @qschmick, thanks for your reply. 

Yes, you are right. I am using something else are you can see below: 

```
namespace App\Console;
use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;
class Kernel extends ConsoleKernel
{
    protected $commands = [
        'App\Console\Commands\CallRoute',
    ];
    protected function schedule(Schedule $schedule)
    {...
    }
```

Regardless of the above, the question is how can I run a given URL with some parameters, like the example mentioned before, `/api/v1/test?api_key=1234567890`. 

I will use anything you recommend. 

Thanks!

**Comment by sergionader** [comment]
Hello, @qschmick

Any updates on this one?

**Comment by qschmick** [comment]
@sergionader I don't have an answer at this moment. I asked about the commands signature. Can you provide that? It should look something like this:

```
protected $signature = 'kitchen:create-sandwich
        {--mayo : If passed, mayo will be added}
        {--cheese-slices=0 : Number of cheese slices to be added}
        {--additional-toppings= : Comma separated lists of toppings to be added}';
```

This way I can figure out how your command is being parsed by artisan/Laravel and see what we can build to match it.

**Comment by sergionader** [comment]
@qschmick,

Thanks for your reply. Please see below the full file, what includes the signature as well. 

app/Console/Commands/CallRoute.php
```
<?php
namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Http\Request;

class CallRoute extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'route:call {uri}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'php artsian route:call /route';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $request = Request::create($this->argument('uri'), 'GET');
        $this->info(app()->make(\Illuminate\Contracts\Http\Kernel::class)->handle($request));
    }

}
```

**Comment by b-roberts** [comment]
PR #196 should resolve this issue.
