### ISSUE TITLE
Bug on use table_prefix

### ISSUE THREAD

**Issue by gcdsm12** [codestudiollc/laravel-totem#195]
I add table_prefix to 'totem_' and generate this error:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'vrcg_core.totem_totem_totem_task_frequencies' doesn't exist (SQL: delete from `totem_totem_totem_task_frequencies` where `id` = 1)

I alter file TotemModel.php to check if already exist totem_ on name table. Please check and fix.

i changed to below:

<?php

namespace Studio\Totem;

use Illuminate\Database\Eloquent\Model;

class TotemModel extends Model
{
    /**
     * @return mixed
     */
    public function getTable()
    {
        $table = parent::getTable();
        if( substr($table,0,strlen(config('totem.table_prefix'))) == config('totem.table_prefix') ){
            return parent::getTable();
        } else {
            return config('totem.table_prefix').$table;
        }
    }
}

**Comment by qschmick** [comment]
@gcdsm12 Can you share where you added the `totem_` prefix? Was it within the config file?

Also, your message was cut off, looks like you were going to include additional information.

We already have a check in the `TotemModel.php` file on line 16 to check if the prefix is within the `parent::getTable` value.

Thanks for any extra insight.

**Comment by gcdsm12** [comment]
yes, i add in my config file config/totem.php.

my totemmodel and config file in attachment.

totemmodel I changes to working.


[TotemModel.php.txt](https://github.com/codestudiohq/laravel-totem/files/3757138/TotemModel.php.txt)
[totem.php.txt](https://github.com/codestudiohq/laravel-totem/files/3757139/totem.php.txt)

**Comment by qschmick** [comment]
@gcdsm12 Thanks for the updated info. A few quick items

- What version of Totem do you have installed?
- We already have the `TotemModel` checking for the prefix (https://github.com/codestudiohq/laravel-totem/blob/5.0/src/TotemModel.php#L16)
- As an FYI, we setup the prefix in a const so you don't have to use the `config` call (https://github.com/codestudiohq/laravel-totem/blob/5.0/src/Providers/TotemServiceProvider.php#L63)
