### ISSUE TITLE
migration error on alter duration

### ISSUE THREAD

**Issue by jagDanJu** [codestudiollc/laravel-totem#204]
Hey,

after installing and executing "php artisan migrate" i´am getting the following error:

![image](https://user-images.githubusercontent.com/3613218/69029925-865b4080-09d6-11ea-9a27-0cab4048ac8e.png)

The point is following migration, which don´t work on postgresql:

![image](https://user-images.githubusercontent.com/3613218/69029993-9d9a2e00-09d6-11ea-998d-a517c3fadfb8.png)

**Comment by gofishwbeeler** [comment]
Yeah, I'm getting the same. 

I'm using Mysql, and Laravel 6.3+, PHP 7.2+ on Valet.

**Comment by jtallant** [comment]
same issue here, mysql, Laravel 6.0, php 7.2

**Comment by thindery** [comment]
I am having the same issue:

php 7.3.2
mysql 5.7.26
laravel 6.5.2

**Comment by myorb** [comment]
+1 

php: 7.3
postgres: 11 
Laravel: 6

**Comment by jorgemudry** [comment]
I've created a new PR to (at least temporarily) fix this issue: https://github.com/codestudiohq/laravel-totem/pull/207

**Comment by jorgemudry** [comment]
Could anyone review the PR to fix the issue, please?

**Comment by vesper8** [comment]
@jorgemudry this PR is only for your new version 6? isn't that leaving all your v5 users in the dust? I haven't upgraded to Laravel 6 and now I can't use this package anymore

**Comment by qschmick** [comment]
@vesper8 Just an FYI, @jorgemudry is just helping by opening the PR they aren't the maintainer.

**Comment by vesper8** [comment]
ah my bad, I saw his name in a couple of places and assumed he was
