### ISSUE TITLE
Postgres Migrate Error

### ISSUE THREAD

**Issue by xyrintech** [codestudiollc/laravel-totem#209]
`php artisan migrate`

throws following error:

```
SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "duration" cannot be cast automatically to type numeric
HINT:  You might need to specify "USING duration::numeric(24,14)". (SQL: ALTER TABLE task_results ALTER duration TYPE NUMERIC(24, 14))
```

**Comment by aldozumaran** [comment]
same problem!!

  SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "duration" cannot be cast automatically to type numeric
HINT:  You might need to specify "USING duration::numeric(24,14)". (SQL: ALTER TABLE task_results ALTER duration TYPE NUMERIC(24, 14))

**Comment by aldozumaran** [comment]
> `php artisan migrate`
> 
> throws following error:
> 
> ```
> SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "duration" cannot be cast automatically to type numeric
> HINT:  You might need to specify "USING duration::numeric(24,14)". (SQL: ALTER TABLE task_results ALTER duration TYPE NUMERIC(24, 14))
> ```

how did you solve it?
