### ISSUE TITLE
allow users to use their own migrations instead of the ones inside the vendor folder

### ISSUE THREAD

**Issue by vesper8** [codestudiollc/laravel-totem#212]
Many other packages allow the user to use their own migrations instead of using the package ones.. this would have allowed us to resolve the error with the duration field quicker without needing to wait for you to merge a fix.. and there are other reasons why we might want this for example if we want to add extra custom columns.

Could you please add a configuration option which if set to true would skip the package migrations and expect the user to take care of that on their own?

That would be appreciated. And please also add it to v5 : )

Thank you!

**Comment by qschmick** [comment]
@vesper8 I've never experienced that need or implementation. Do you have any examples of packages doing this? Always feel free to open a PR and we can review and get it incorporated. Thanks for the feedback :)

**Comment by vesper8** [comment]
Here is an example of a popular package that does exactly this
https://github.com/cybercog/laravel-love/blob/master/config/love.php#L33-L43

I guess perhaps a more common practice is to have the user publish the migrations and then run those instead of running migrations from the vendor folder.

Some packages that I use that do this are
https://github.com/vsch/laravel-translation-manager
and
https://github.com/laravel-notification-channels/webpush

There are many others

Anyway I am just frustrated that as a result of a migration that I cannot change easily without forking the package, my whole application won't run composer anymore. This could have been alleviated through either of the above practices

**Comment by vesper8** [comment]
this would still be a nice-to-have, if you don't want to add it I completely understand and you can close this issue.. but it shouldn't be stale bot's responsibility to do so
