### ISSUE TITLE
Last Run Time Always in UTC

### ISSUE THREAD

**Issue by eFlowMedia** [codestudiollc/laravel-totem#214]
Hello. I noticed that the Last Run time in the platform is UTC, while the Next Run time is the timezone set in the task.  The two tasks in the middle were run at 8:01 UTC, and the next scheduled run is 1/25 @ 00:01 PST.

<img width="711" alt="Screen Shot 2020-01-18 at 9 42 49 AM" src="https://user-images.githubusercontent.com/16480031/72668023-233a5a00-39d7-11ea-8cc6-61957fc8840c.png">

**Comment by eFlowMedia** [comment]
Also I noticed that if the next run time (directly transposed to UTC), it will show that it will be skipped in showing in the Next Run.  I bit confusing so let me give an example.

The time for these jobs to be run are weekly on Saturday @ 00:01 (PST 1 0 * * * 6).  When I logged in last nigh(1/17 @ 10pm PST)t to make sure it was going to work correctly, it showed the next run time to be 1/25 @ 00:01, when in actuality the next run was within a couple of hours at 1/18 @ 00:01 (PST).  I think its because there is a UTC vs local time mixup with the next run field.  Like it is calculating the next run based on UTC, but showing it in the PST.  So since there was a 8 hr spread and technically if you converted the cron to exactly UTC @ (1 0 * * * 6), it already passed (Because UTC 1/18 @ 00:01 was a couple hours before at this time of checking 10am PST or 2am UTC)  and thats why its showing the next run to be next week, when in actuality it was in a few hours.  

Now don't get me wrong, it did run properly at the right time, It's just the Last Run & Next Run are not consistent timezones, and calculating in not-consistent timezones (if that makes any sense).

**Comment by eFlowMedia** [comment]
bump

**Comment by prakhargvp** [comment]
@roshangautam. I'm also geeting same issue.

- This Task is running on hourly basis. But last run showing wrong time.

![image](https://user-images.githubusercontent.com/7056772/89479587-d40c1900-d7b0-11ea-82c8-d0e4b09c37b0.png)

![image](https://user-images.githubusercontent.com/7056772/89479567-cb1b4780-d7b0-11ea-894d-36ab18127041.png)


If you see ran_at is in UTC. While created_at and updated_at column is in Asia/Kolkata (correct timezone).

![image](https://user-images.githubusercontent.com/7056772/89479505-a1622080-d7b0-11ea-8d2d-082840329a4a.png)
