### ISSUE TITLE
Class 'Str' not found

### ISSUE THREAD

**Issue by andrewwindfall** [codestudiollc/laravel-totem#217]
/vendor/studio/laravel-totem/resources/views/tasks/view.blade.php
`
line 16:  <span class="uk-float-left">{{Str::limit($task->description, 80)}}</span>
`

This should be:
`
   <span class="uk-float-left">{{Illuminate\Support\Str::limit($task->description, 80)}}</span>
`
for laravel 6

**Comment by timothyasp** [comment]
Add 

```
'Arr' => Illuminate\Support\Arr::class,
'Str' => Illuminate\Support\Str::class,
```

to your `config/app.php` aliases list.
