### ISSUE TITLE
Cant install laravel-totem in my project

### ISSUE THREAD

**Issue by matthieumarais** [codestudiollc/laravel-totem#233]
Windows 10
laravel/framework": "5.8.*"
laravel/horizon": "^3.2"

When I execute this cmd `composer require studio/laravel-totem --ignore-platform-reqs`
I have this error ...
`Problem 1
    - Conclusion: remove laravel/framework v5.8.38
    - Conclusion: don't install laravel/framework v5.8.38
    - studio/laravel-totem 7.0.x-dev requires illuminate/notifications ^7.0 -> satisfiable by illuminate/notifications[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3,
v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.2.0, v7.2.1, v7.2.2, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - studio/laravel-totem v7.0.0 requires illuminate/notifications ^7.0 -> satisfiable by illuminate/notifications[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.
10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.2.0, v7.2.1, v7.2.2, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.0.0|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.0.1|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.0.2|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.0.3|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.0.4|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.0.5|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.0.6|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.0.7|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.0.8|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.1.0|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.1.1|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.1.2|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.1.3|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.10.0|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.10.1|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.10.2|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.10.3|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.11.0|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.12.0|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.13.0|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.14.0|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.14.1|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.2.0|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.2.1|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.2.2|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.3.0|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.4.0|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.5.0|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.5.1|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.5.2|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.6.0|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.6.1|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.6.2|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.7.0|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.7.1|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.8.0|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.8.1|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.9.0|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.9.1|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications v7.9.2|don't install laravel/framework v5.8.38
    - Installation request for laravel/framework (locked at v5.8.38, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.38].
    - Installation request for studio/laravel-totem ^7.0 -> satisfiable by studio/laravel-totem[7.0.x-dev, v7.0.0].`

When I try to add illuminate/notifications package, I have the same error
`Problem 1
    - Conclusion: don't install illuminate/notifications v7.14.1
    - Conclusion: don't install illuminate/notifications v7.14.0
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.0
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.1
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.10
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.11
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.12
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.13
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.14
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.15
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.16
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.17
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.18
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.19
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.2
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.20
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.21
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.22
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.23
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.24
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.25
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.26
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.27
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.28
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.29
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.3
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.30
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.31
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.32
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.33
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.34
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.35
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.36
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.37
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.38
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.4
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.5
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.6
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.7
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.8
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.9
    - don't install illuminate/notifications 7.x-dev|remove laravel/framework v5.8.38
    - don't install illuminate/notifications 7.x-dev|don't install laravel/framework v5.8.38
    - Installation request for illuminate/notifications ^7.14 -> satisfiable by illuminate/notifications[7.x-dev, v7.14.0, v7.14.1].
    - Installation request for laravel/framework 5.8.* -> satisfiable by laravel/framework[5.8.x-dev, v5.8.0, v5.8.1, v5.8.10, v5.8.11, v5.8.12, v5.8.13, v5.8.14, v5.8.15, v5.8.16, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.21
, v5.8.22, v5.8.23, v5.8.24, v5.8.25, v5.8.26, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.37, v5.8.38, v5.8.4, v5.8.5, v5.8.6, v5.8.7, v5.8.8, v5.8.9].`

I dont know where is the matter

Thanks 4 help

**Comment by roshangautam** [comment]
use Totem v5.x  with Laravel v5.8. This is shown in the compatibility matrix in readme. Also we align with the same support policy as Laravel when it comes to supporting old versions. You can find more details here : https://laravel.com/docs/7.x/releases

**Comment by matthieumarais** [comment]
My bad sry ... it wasn't written big enough XD

Thanks a lot
