### ISSUE TITLE
Add support for Laravel 8

### ISSUE THREAD

**Issue by nickfls** [codestudiollc/laravel-totem#244]
Will it be possible to add support for Laravel 8?

**Comment by rconte84** [comment]
Any news?

**Comment by roshangautam** [comment]
feel free to send a PR, I would be more than happy to review and merge

**Comment by inoprime** [comment]
#249 Added please merge ASAP.

**Comment by Drivez** [comment]
Any news on this?

**Comment by daniel-g-wood** [comment]
Just created [#253 ](https://github.com/codestudiohq/laravel-totem/pull/253) which also upgrades the model factories.

**Comment by roshangautam** [comment]
#253 has been merged and released. Thank you @daniel-g-wood
