### ISSUE TITLE
Migration problem

### ISSUE THREAD

**Issue by aldozumaran** [codestudiollc/laravel-totem#245]
I can't istall package, i have a problem with migration
![image](https://user-images.githubusercontent.com/3183704/92915218-a5770300-f42c-11ea-88a1-f91ce963e269.png)

postgresql 12
php 7.4
ubuntu 18.04

**Comment by qschmick** [comment]
@aldozumaran Should be fixed in my PR #251

**Comment by qschmick** [comment]
Fixed in release https://github.com/codestudiohq/laravel-totem/releases/tag/v7.0.2
