### ISSUE TITLE
Migration is failed on Postgres

### ISSUE THREAD

**Issue by akimkelar** [codestudiollc/laravel-totem#250]
Migration is failed on Postgres with error:
`Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "duration" cannot be cast automatically to type numeric
HINT:  You might need to specify "USING duration::numeric(24,14)".")`

Caused by query
`ALTER TABLE task_results ALTER duration TYPE NUMERIC(24, 14)`
in script
vendor/studio/laravel-totem/database/migrations/2019_09_25_103421_update_task_results_duration_type.php:19

**Comment by akimkelar** [comment]
Solved like this
```
public function up()
    {
        Schema::connection(TOTEM_DATABASE_CONNECTION)
            ->table(TOTEM_TABLE_PREFIX.'task_results', function (Blueprint $table) {
                $table->dropColumn('duration');
            });

        Schema::connection(TOTEM_DATABASE_CONNECTION)
            ->table(TOTEM_TABLE_PREFIX.'task_results', function (Blueprint $table) {
                $table->decimal('duration', 24, 14);
            });
    }
```

**Comment by qschmick** [comment]
@akimkelar Should be fixed in my PR #251

**Comment by qschmick** [comment]
Fixed in release https://github.com/codestudiohq/laravel-totem/releases/tag/v7.0.2

**Comment by aldozumaran** [comment]
![image](https://user-images.githubusercontent.com/3183704/97689669-3c128880-1a9c-11eb-9303-3c9c8530b3af.png)
