### ISSUE TITLE
Gotting Be Right Back in production

### ISSUE THREAD

**Issue by ghost** [codestudiollc/laravel-totem#254]
I'm with totem installed in development and prodution, in development everything work fine, but when I try to access totem route in production I got "Be Right Back" message from laravel.

Anybody knows why this happening and how can I debug it?

**Comment by qschmick** [comment]
@tribunaldoconsumidor A couple of questions:
- What version of Laravel are you running
- What version of Totem do you have installed
- Are you able to access any other portions of your site/project in production?

The "Be Right Back" message is the message when you application is in maintenance mode. If you are not able to access anything in production then you might need to bring your app up or you might be missing a `.env` file.

**Comment by ghost** [comment]
@qschmick Laravel 8
I'm using one version of Totem that I forked to support laravel 8, but the changes in this fork is just version of libs as I said to support laravel 8

I'm pretty able to access any other part of project in production, just Totem give me back "Be Right back" message.

The .env file is there and configured

**Comment by inoprime** [comment]
Same error here. Just trying to access totem tasks list and gotting "Be Right Back" message.

The entire application its working normaly just totem gotting this error.

**Comment by inoprime** [comment]
The behavior what I indetify is, when my .env is with APP_ENV=production, I got "Be Right Back" message, but when APP_ENV=local it works.

How do I do to APP_ENV=production release the access to totem?
