### ISSUE TITLE
Migrate Error Tag v8.0 not update file 2019_09_25_103421_update_task_results_duration_type.php (20 day)

### ISSUE THREAD

**Issue by apiruknetway** [codestudiollc/laravel-totem#260]
Please tag version 8.0.1 to update file 

branch 8.0
https://github.com/codestudiohq/laravel-totem/blob/8.0/database/migrations/2019_09_25_103421_update_task_results_duration_type.php (6 day)

tag v8.0 not update 
https://github.com/codestudiohq/laravel-totem/blob/v8.0/database/migrations/2019_09_25_103421_update_task_results_duration_type.php (20 day)

**Comment by qschmick** [comment]
@apiruknetway Please see https://github.com/codestudiohq/laravel-totem/releases/tag/v8.0.1

**Comment by apiruknetway** [comment]
Thank you very much. @qschmick
