### ISSUE TITLE
Totem 6.x +Postgresql = column "duration" cannot be cast automatically to type numeric

### ISSUE THREAD

**Issue by viccatoff** [codestudiollc/laravel-totem#262]
I have an error while migrating database:

```
SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "duration" cannot be cast automatically to type numeric
  HINT:  You might need to specify "USING duration::numeric(24,14)". (SQL: ALTER TABLE totemtask_results ALTER duration TYPE NUMERIC(24, 14))
```

 I know it was fixed in https://github.com/codestudiohq/laravel-totem/pull/251, but it's not fixed for version 6.x. Do you support this version? I'm using it, because we can't update right now to laravel 7/8.

**Comment by qschmick** [comment]
@viccatoff Can you open a PR with the fix from #251 pointing to the 6.x repo and we can take a look at that?
