### ISSUE TITLE
Allow database cache driver for onOneServer

### ISSUE THREAD

**Issue by jonah-dev** [codestudiollc/laravel-totem#265]
Per the documentation: https://laravel.com/docs/8.x/scheduling#running-tasks-on-one-server

You should be able to use onOneServer() when using the database driver, but it's currently not supported here. Is there any reason to disallow the use of the database driver? If not, I can create a pull request for this.

https://github.com/codestudiohq/laravel-totem/blob/8.0/src/Providers/ConsoleServiceProvider.php#L53-L55

**Comment by qschmick** [comment]
@jonah-dev Feel free to open a PR for review.

**Comment by jonah-dev** [comment]
@qschmick I believe this can be closed. Not sure if you wish to link the PR associated with it. https://github.com/codestudiohq/laravel-totem/pull/269 but I don't seem to be able to.
