### ISSUE TITLE
Fix search if url ?q  not isset

### ISSUE THREAD

**Issue by CrazyBoy49z** [codestudiollc/laravel-totem#268]
In production if request totem/tasks show empty tasks, if add totem/tasks?q= tasks shows

![image](https://user-images.githubusercontent.com/3448603/105152751-4464e780-5b10-11eb-86e5-cb1197235158.png)

**Comment by qschmick** [comment]
@CrazyBoy49z Can you please provide a few extra details to help with debugging this issues:
- What PHP version
- What Laravel version
- What Totem version

**Comment by CrazyBoy49z** [comment]
php: 7.4
Laravel Framework: 8.22.1
laravel-totem: "^8.0"

**Comment by CrazyBoy49z** [comment]
up
