### ISSUE TITLE
[Proposal] Notifications for Failed Tasks Only

### ISSUE THREAD

**Issue by daniel-g-wood** [codestudiollc/laravel-totem#275]
Currently, notifications can only be sent when a task is executed. When there are a lot of scheduled tasks, each running at relatively frequent intervals, the amount of notifications can potentially get quite overwhelming, and failed tasks might be lost in all the 'noise'.

I'd like to work up a PR that allows notifications to only be sent when a task fails, i.e. in the interface, add a checkbox under each notification channel (Email/SMS/Slack) saying something like "Only send notifications when task fails".

This would then only send notifications to that channel if one of the following was true:

1. The task returns a non-zero status code
2. The task raises an exception

I think this would be a helpful feature to add. If you are happy for me to go ahead, then I'll work on a PR over the next couple of weeks along with relevant tests to submit for review.

**Comment by qschmick** [comment]
@daniel-g-wood I think that would be a great feature.

**Comment by daniel-g-wood** [comment]
Great, I'll start work on it!
