### ISSUE TITLE
Schedule list not refreshing after creating new task

### ISSUE THREAD

**Issue by ketbla** [codestudiollc/laravel-totem#277]
Hi,

I'm using Totem but noticed that Totem doesn't pick up new tasks unless I clear:cache. However if I delete a task - it the refreshes the list. Why comes it doesn't refresh after creating new task?

**Comment by ketbla** [comment]
According to listeners and events, it should bust cache when adding new task, but that's not working in my case.
I'm using Redis driver for cache.

protected $listen = [
        'Studio\Totem\Events\Created'     => ['Studio\Totem\Listeners\BustCache', 'Studio\Totem\Listeners\BuildCache'],
        'Studio\Totem\Events\Updated'     => ['Studio\Totem\Listeners\BustCache', 'Studio\Totem\Listeners\BuildCache'],
        'Studio\Totem\Events\Activated'   => ['Studio\Totem\Listeners\BustCache', 'Studio\Totem\Listeners\BuildCache'],
        'Studio\Totem\Events\Deactivated' => ['Studio\Totem\Listeners\BustCache', 'Studio\Totem\Listeners\BuildCache'],
        'Studio\Totem\Events\Deleting'    => ['Studio\Totem\Listeners\BustCacheImmediately'],
    ];

**Comment by bondas83** [comment]
Maybe you forgot start queues
