### ISSUE TITLE
Task Results not updating on L8

### ISSUE THREAD

**Issue by ikudosi** [codestudiollc/laravel-totem#278]
I am noticing that on L8, the task results are no longer being created. I am 100% certain the tasks are firing because even before implementing Totem, I have separate jobs table to timestamp when each one has fired from within the console command class itself.

I initially implemented this on L6 and was working then... so I'm not sure if I missed something or this is an actual bug.

**Comment by ikudosi** [comment]
Also want to add that if I manually execute the task through the Totem dashboard, the task result is created.

**Comment by daniel-g-wood** [comment]
I had a similar problem and it was related to the storage facade issue that I recently created a fix for (#271). Are you using the latest version of totem?

**Comment by ikudosi** [comment]
@daniel-g-wood When this issue was created I was version 8.1.1. I believe when I initially upgraded to L8 at the time it was on 8.0.4 and tasks were running but noticed no results being recorded. Then I upgraded to 8.1.1 in hopes it would have been corrected but turned out for the worst.

**Comment by ikudosi** [comment]
@daniel-g-wood would a `return 1` in the Command class prevent the results being generated for 8.1.1 if you're saying it's fixed? I just noticed that all of our handle() methods in the console commands return a 1 (although generating a new command defaults to return 0).

**Comment by daniel-g-wood** [comment]
I don't believe a return value of 1 would stop the results being generated as the exit code from the Artisan command is not currently being stored or checked. Although you should be returning 0 if the command is successful.

I'm at a bit of a loss without being able to reproduce the error myself.  If you create a task in totem for a standard Artisan command (e.g. `list` or `help`), then run `schedule:test` from the console and choose that particular task, do you get any results stored in the database? Also try running locally with your queue driver set to `sync` (if you aren't already).
