### ISSUE TITLE
Cannot install on Laravel 8

### ISSUE THREAD

**Issue by krzar** [codestudiollc/laravel-totem#286]
There is problem to install package with Laravel 8, composer throws this error:

`studio/laravel-totem v8.1.1 requires doctrine/dbal ^2.9 -> found doctrine/dbal[v2.9.0, ..., 2.13.x-dev] but the package is fixed to 3.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.`

Totem is using dbal 2.9, when laravel 8 is using 3.1

**Comment by qschmick** [comment]
@KrystianZareba Can you try deleting your `composer.lock` file and try again?

**Comment by mathias1981** [comment]
@qschmick same problem for me, and i tried deleting the composer.lock file, the problem persists.

**Comment by hanmuja-juango** [comment]
same problem here, any solution?

**Comment by hihuangwei** [comment]
希望可以修复

**Comment by aberaldo** [comment]
@qschmick i have the same issue. I cannot install totem in laravel 8! Any idea? Thanks

**Comment by qschmick** [comment]
@KrystianZareba @marcoocram @hanmuja-juango @hihuangwei @aberaldo PR https://github.com/codestudiohq/laravel-totem/pull/296 opened with update to 3.x for dbal.

**Comment by qschmick** [comment]
@KrystianZareba @marcoocram @hanmuja-juango @hihuangwei @aberaldo DBAL 3.x in release: https://github.com/codestudiohq/laravel-totem/releases/tag/v8.3.0
