### ISSUE TITLE
Cannot install on Laravel Vapor

### ISSUE THREAD

**Issue by pastocaza** [codestudiollc/laravel-totem#287]
There is an error when you deploy the code to vapor in the deployment hook.

```json
{
    "message": "Found 1 error while validating the input provided for the PutObject operation:\n[Bucket] is missing and is a required parameter",
    "context": {
        "exception": {
            "class": "InvalidArgumentException",
            "message": "Found 1 error while validating the input provided for the PutObject operation:\n[Bucket] is missing and is a required parameter",
            "code": 0,
            "file": "\/var\/task\/vendor\/aws\/aws-sdk-php\/src\/Api\/Validator.php:65"
        },
        "aws_request_id": "76bfd571-7909-44fd-a043-b0b6c4589b91"
    },
    "level": 400,
    "level_name": "ERROR",
    "channel": "production",
    "datetime": "2021-05-12T17:34:44.898142-04:00",
    "extra": []
}
```

It works normally on forge, local, and digitalocean.

**Comment by qschmick** [comment]
@iRynoh Are you sure the issue is with this library? We don't use AWS S3 which appears to be the issue with the call to PutObject

**Comment by pastocaza** [comment]
It's weird for me too, but I removed the package and the deployment worked again 🤔 I will try to reproduce it in a fresh laravel app.

**Comment by oliworx** [comment]
@iRynoh Did you finally got Totem running on Vapor? 

I have a similar issue during deployment of an Laravel 8 project to Vapor, on the part `artisan package:discover`. It seems a database connection is expected here, during the build process.
