### ISSUE TITLE
Record Limit

### ISSUE THREAD

**Issue by saaiful** [codestudiollc/laravel-totem#289]
Limiting records in the database for totem is important.  I just purged 2Gb data from my database.  Please add an option in config to set the max record limit.

**Comment by qschmick** [comment]
@saaiful This already exists on a per command basis. When you create/edit a command you can set a limit on number of records or age of records and the system will auto purge results over that limit.

E.g.
Number limit of 5000 it will delete all records over the 5000th
Age limit 5 days it will delete all records older than 5 days
