### ISSUE TITLE
L8 Cannot Install Table Missing

### ISSUE THREAD

**Issue by s1rc** [codestudiollc/laravel-totem#290]
Running command `composer require studio/laravel-totem` results in the following error:
```
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'app.task_frequencies' doesn't exist (SQL: select * from `task_frequencies` where `task_frequencies`.`task_id` = 2 and `task_frequencies`.`task_id` is not null)
```

Seems obvious, but we can't run the migration without the package installed.

**Comment by kanhaiyam** [comment]
Have you had totem installed before and are trying to reinstall. 
 Anyways, try this -> #145 

or try it on a fresh installation.

**Comment by s1rc** [comment]
@kanhaiyam thank you that fixed it.
