### ISSUE TITLE
Cannot be executed automatically

### ISSUE THREAD

**Issue by shijie1991** [codestudiollc/laravel-totem#292]
Laravel 8.51.0
totem v8.1.4

![image](https://user-images.githubusercontent.com/11606404/127629982-1fb22975-0a9c-426c-9ade-00dd98aad5ce.png)

![image](https://user-images.githubusercontent.com/11606404/127630027-ef75980c-6d0b-4bc8-b8d1-6c85e37619f0.png)

![image](https://user-images.githubusercontent.com/11606404/127630081-92c15d7c-460b-400c-87c1-b7d2be62e277.png)

![image](https://user-images.githubusercontent.com/11606404/127630122-60f3d25d-0881-45a0-b410-6b9634ad2f96.png)

**Comment by kanhaiyam** [comment]
**Could you please elaborate what the issue is?**

**Comment by shijie1991** [comment]
Laravel 8.51.0
totem v8.1.4
1. 设置定时任务 并将输出打印到文件
![image](https://user-images.githubusercontent.com/11606404/127629982-1fb22975-0a9c-426c-9ade-00dd98aad5ce.png)
 2.查看输出的 corn 日志(已执行)
![image](https://user-images.githubusercontent.com/11606404/127630027-ef75980c-6d0b-4bc8-b8d1-6c85e37619f0.png)
 3.test 文件 将 记录日志到 laravel.log
![image](https://user-images.githubusercontent.com/11606404/127630081-92c15d7c-460b-400c-87c1-b7d2be62e277.png)
4.并没有执行 Log::debug (未执行)
![image](https://user-images.githubusercontent.com/11606404/127630122-60f3d25d-0881-45a0-b410-6b9634ad2f96.png)

**Comment by shijie1991** [comment]
I use Alibaba Cloud as file storage

`$event->cron($task->getCronExpression())
                ->name($task->description)
                ->timezone($task->timezone)
                ->before(function () use ($task, $event) {
                    $event->start = microtime(true);
                    Executing::dispatch($task);
                })
                ->after(function () use ($event, $task) {
                    Executed::dispatch($task, $event->start ?? microtime(true));
                })
                ->sendOutputTo(Storage::path($task->getMutexName()));`

Unsuccessful here makes it impossible to execute

`sendOutputTo(Storage::path($task->getMutexName()))`
