### ISSUE TITLE
Cannot be executed automatically

### ISSUE THREAD

**Issue by shijie1991** [codestudiollc/laravel-totem#293]
I use Alibaba Cloud as file storage

`$event->cron($task->getCronExpression()) ->name($task->description) ->timezone($task->timezone) ->before(function () use ($task, $event) { $event->start = microtime(true); Executing::dispatch($task); }) ->after(function () use ($event, $task) { Executed::dispatch($task, $event->start ?? microtime(true)); }) ->sendOutputTo(Storage::path($task->getMutexName()));`

Unsuccessful here makes it impossible to execute

`sendOutputTo(Storage::path($task->getMutexName()))`

**Comment by shijie1991** [comment]
Can I only use local storage????

**Comment by qschmick** [comment]
@shijie1991 Apologies for the lack of response, work and life have been busy. #295 Looks to solve this issue. I'm going to close this issue in favor of that one with a proposed solution.
