### ISSUE TITLE
[Proposal] add support for environment constraints

### ISSUE THREAD

**Issue by shawnheide** [codestudiollc/laravel-totem#294]
Just wanted to see if there was any interest in adding support for the [environment constraints](https://laravel.com/docs/8.x/scheduling#environment-constraints) option? I'm happy to look into it further and submit a PR.

**Comment by qschmick** [comment]
@shawnheide What is the use case you're thinking of for this? The totem tasks are stored in the DB. Would this be for running multiple instances of code against the same DB/Schema?

I'm open to the idea just wonder what value it brings

**Comment by shawnheide** [comment]
@qschmick I was just looking into switching to totem, so I think I didn't think through that it's stored in the DB. Agreed, probably not necessary. Thanks.
