### ISSUE TITLE
[Proposal] Replace storage logs by passing output directly to events

### ISSUE THREAD

**Issue by shawnheide** [codestudiollc/laravel-totem#295]
Not sure if there is another reason for using the storage logs, but they could be dropped by passing the output directly to the events using `thenWithOutput` in the ConsoleServiceProvider. I already made the changes and tested it locally, but let me know if there is anything else to consider.

[Branch with changes](https://github.com/uwpsych/laravel-totem/tree/refactor/feature%2Fdrop-storage)

**Comment by shijie1991** [comment]
支持!!!

**Comment by qschmick** [comment]
@shawnheide Firstly, thanks for the contribution and work. Secondly, yes, please open this PR. 🚀

**Comment by shawnheide** [comment]
Happy to help. I just submitted the PR.
