### ISSUE TITLE
Got lazy load [frequencies]

### ISSUE THREAD

**Issue by locnguyen1842** [codestudiollc/laravel-totem#300]
Hi, I got a lazy load exception on the tasks list view when the model `preventLazyLoading` turned on in laravel 8
Exception message:
`Attempted to lazy load [frequencies] on model [Studio\Totem\Task] but lazy loading is disabled.`

**Comment by o-kima** [comment]
@locnguyen1842 Does PR https://github.com/codestudiohq/laravel-totem/pull/302 help you?

it's just merged to v8.3

**Comment by locnguyen1842** [comment]
@o-kima yes, it did. Thanks for reminding me.
