### ISSUE TITLE
Totem task_frequencies queries present in every request

### ISSUE THREAD

**Issue by s1rc** [codestudiollc/laravel-totem#301]
Every request made outside of Totem routes still has totem queries such as:

```sql
select
  *
from
  `totem_task_frequencies`
where
  `totem_task_frequencies`.`task_id` = 1
  and `totem_task_frequencies`.`task_id` is not null
```
and
```sql
select
  *
from
  `totem_frequency_parameters`
where
  `totem_frequency_parameters`.`frequency_id` in (1)
```

Is there a reason these queries and cache hits are running on all requests?

**Comment by o-kima** [comment]
what cache driver do you use?

**Comment by s1rc** [comment]
Redis.

**Comment by o-kima** [comment]
This happens as totem register his task to the scheduler in every app bootstrap, and not only in Console Kernel.
Here is my [Pull Request](https://github.com/codestudiohq/laravel-totem/pull/299) for this.

**Comment by o-kima** [comment]
Added new PR for that specific frequencies query
https://github.com/codestudiohq/laravel-totem/pull/302

**Comment by s1rc** [comment]
@o-kima awesome thank you. Hopefully your PRs can be reviewed soon.

**Comment by qschmick** [comment]
@s1rc New release with update from @o-kima  https://github.com/codestudiohq/laravel-totem/releases/tag/v8.3.0

**Comment by s1rc** [comment]
@qschmick thank you! 

Testing this out, I see the Redis cache hits on every request. This is more ideal than querying the DB, is there a way to register the task in only the console kernel?

**Comment by o-kima** [comment]
Please add more details like what cache key it search and where it occurs in the flow.
I just retested it in my app, listening to CacheHit|CacheMissed, no requests found in HTTP kernel.

Fixed at commit https://github.com/codestudiohq/laravel-totem/pull/299/commits/65c8e3d3e6eb2cf22c267f2388755ae587f709da

**Comment by s1rc** [comment]
Looking at Telescope, even on requests with no queries aside from session these are run:
* `get app_cache:totem.tasks.active`
* `get app_cache:totem.table.totem_tasks`

Edit: I added a listener to `EventServiceProvider` for `Illuminate\Cache\Events\CacheHit` in case Telescope was mis-reporting. Both those are returning hits from every request.
