### ISSUE TITLE
Route totem.task.execute is outside the middleware (auth)

### ISSUE THREAD

**Issue by Nino1976** [codestudiollc/laravel-totem#304]
After adding [**Totem::auth() ...**] to [**AppServiceProvider**], the route [**totem.task.execute**] has no authentication. Is that correct? All other totem routes correctly return 403, if the user is not logged in or has no rights or no authorization.

best regards, nino

**Comment by jacktran** [comment]
@Nino1976 any solution for this issue ?
i think this's security issue 
seem like it's missing parent::__contruct() in https://github.com/codestudiohq/laravel-totem/blob/8.0/src/Http/Controllers/ExecuteTasksController.php
![image](https://user-images.githubusercontent.com/8914866/151688872-05599d54-7a4c-418c-b385-039f7af71aed.png)

**Comment by qschmick** [comment]
@jacktran @Nino1976 Yes, looks like there is a missing call to parent __construct. Can either of you open a PR

**Comment by jacktran** [comment]
hi @qschmick i don't have permission to create PR
![image](https://user-images.githubusercontent.com/8914866/153760361-2adc123f-5578-4485-9365-5eba46172566.png)
Or can you please help to create PR for it ?

**Comment by qschmick** [comment]
@jacktran You can fork and open the PR from there pointing at this repo
