### ISSUE TITLE
Can't Pass Single Command Parameter Without a name

### ISSUE THREAD

**Issue by oliworx** [codestudiollc/laravel-totem#307]
this one is similar to https://github.com/codestudiohq/laravel-totem/issues/48 but different.

I have a command that takes the ID of a model as a parameter:

`$signature = 'team:matomo:setup {teamId}'`

when I create a Task in Totem with just an integer as a parameter, and execute the task, the command complains that the parameter is missing.

running the same command in a terminal or in the unit tests everything is ok.

running Totem 6.0.3  / Laravel 6.20 / PHP 7.4

**Comment by qschmick** [comment]
@oliworx Just to be clear, the command works fine when it runs on a schedule but fails when you click the checkmark on the main screen or the manual execute button on the task view screen?

**Comment by oliworx** [comment]
I did not try to run the command on schedule. I just wantet to run the command once via the execute button.

**Comment by affektde** [comment]
Did you use the following syntax in the create task view?

eg.

` teamId=1` as optional parameter

Because you've said "without a name", but the name would be `teamId`.
