### ISSUE TITLE
N+1 problem

### ISSUE THREAD

**Issue by usernotnull** [codestudiollc/laravel-totem#309]
I have Model::preventLazyLoading(app()->isLocal()); in my service provider to avoid n+1 issues.

When entering totem dashboard, I get 

```Attempted to lazy load [frequencies] on model [Studio\Totem\Task] but lazy loading is disabled. (View: /home/john/Sites/marvelcoding.com/vendor/studio/laravel-totem/resources/views/tasks/index.blade.php)```

I can temporarily get around it by commenting out preventLazyLoading, but the solution is not optimal.

Is there a plan to resolve this issue?

**Comment by qschmick** [comment]
@usernotnull I don't have time immediately to tackle this, but if you're willing to open a PR we'd be happy to review and get a new version released. Otherwise we might get this fixed by EOY or early January

**Comment by usernotnull** [comment]
Alright. I have to finish a project first. If this wasn't resolved by January I'll give it a go.
Thanks.

**Comment by qschmick** [comment]
Thanks @locnguyen1842 

FYI @usernotnull -> https://github.com/codestudiohq/laravel-totem/releases/tag/v8.3.2
