### ISSUE TITLE
Forbidden error on PREPROD environment

### ISSUE THREAD

**Issue by marcelohcortez** [codestudiollc/laravel-totem#311]
So I can run Totem correctly on my local environment, but we need it to work in our PREPROD environment.
I added a Middleware to check if the user is an admin or super-admin.
If not, the user is redirected to the home, if so, the Totem dashboard is shown.
It works as expected locally, but once in PREPROD I keep getting a 403 error if I'm logged as admin (or super-admin).
If I'm not logged or if I'm logged with other acc, the redirect happens as expected.
Is there any type of block on the plugin that could be causing that?

**Comment by qschmick** [comment]
@marcelohcortez Did you update the AppServiceProvider? https://github.com/codestudiohq/laravel-totem#web-dashboard

**Comment by dangnhdev** [comment]
```php
public static ?Closure $authUsing = null;

    /**
     * Determine if the given request can access the Totem dashboard.
     *
     * @param  Request|string|null  $request
     * @return bool
     */
    public static function check($request): bool
    {
        return (static::$authUsing ?: function () {
            return app()->environment('local');
        })($request);
    }
```
I've encountered the same issue. At the moment, my system lacks an authentication mechanism, and by default, this snippet of code causes Totem to return a 403 error when the system is **NOT** in local environment.

I propose that we designate [this section](https://github.com/codestudiohq/laravel-totem#web-dashboard) in the README as mandatory if the system does not incorporate an authentication mechanism. This clarification will be instrumental in aiding users to configure their systems correctly and avoid similar issues.
