### ISSUE TITLE
Laravel 9 support?

### ISSUE THREAD

**Issue by dyanakiev** [codestudiollc/laravel-totem#313]
Hello,
Is there some incopatability with laravel 9?

**Comment by shijie1991** [comment]
+1

**Comment by qschmick** [comment]
@dyanakiev @shijie1991 Working on it https://github.com/codestudiohq/laravel-totem/pull/314

**Comment by miguelfspinto** [comment]
+1

**Comment by javis** [comment]
+1

**Comment by qschmick** [comment]
https://github.com/codestudiohq/laravel-totem/releases/tag/v9.0.0
