### ISSUE TITLE
Running out of memory in AVG RUN TIME

### ISSUE THREAD

**Issue by Situ314** [codestudiollc/laravel-totem#321]
I'm having trouble trying to access the page to view/edit some of my Tasks. The message "Allowed memory size of 268435456 bytes exhausted" occurs specifically in the AVG RUN TIME, one of these tasks in which I have problems has 30 task_results, but the duration is 6 digits for each. 

Is there something I can do from my side?

I am using Laravel 8, and Totem 8.2.0. I'm not sure I can update it, or increase the memory at the moment.

Thank you very much in advance!

**Comment by qschmick** [comment]
@Situ314 This was fixed/optimized in https://github.com/codestudiohq/laravel-totem/releases/tag/v8.3.3
