### ISSUE TITLE
Column not found: 1054 Unknown column 'run_in_background'

### ISSUE THREAD

**Issue by TelMercher** [codestudiollc/laravel-totem#323]
Hi,
when i try to save a task i have this error: Column not found: 1054 Unknown column 'run_in_background' in 'field list' (SQL: insert into `totem_tasks` [...])

Did anyone have the same error?

**Comment by qschmick** [comment]
@TelMercher 
1. Which version of Totem are you running?
2. Have you run `php artisan migrate` to ensure the DB is up to date?

**Comment by TelMercher** [comment]
Ver. 8.4. 
Yes, i did. I have checked in migrations and the column is not there.

**Comment by qschmick** [comment]
@TelMercher Please verify that this migration has run in you system: https://github.com/codestudiohq/laravel-totem/blob/8.0/database/migrations/2020_12_10_120000_alter_tasks_table_add_run_in_background_support.php

This has existed for over a year.

**Comment by TelMercher** [comment]
I have checked but that migration is not present. I don't understand what happened.

**Comment by qschmick** [comment]
@TelMercher Sounds like the migration just needs to be run. If you run `php artisan migrate` does it state that there are no migrations to run? If that migration doesn't exist in your `migrations` table and it isn't running it sounds like there might be a problem with your setup.

1. Do you have `vendor/` committed or is it created/installed on deployment?
1. What about in your local environment?
1. Can you rebuild locally and it works or same issue?
1. Have you added added/changed the table prefix value? If the table was originally created with a different prefix that could be an issue
