### ISSUE TITLE
Migration error v4.0

### ISSUE THREAD

**Issue by tiagorodriguesnes** [codestudiollc/laravel-totem#334]
2018_07_06_165603_add_indexes_for_tasks.php on branch 4.0 should drop fk `task_id_fk` instead of `task_results_task_id_fk` on line 53 causing the rollback to fail.

**Comment by qschmick** [comment]
@2092015 Any chance you can open a PR to fix the issue?

**Comment by tiagorodriguesnes** [comment]
Sure

**Comment by tiagorodriguesnes** [comment]
https://github.com/codestudiohq/laravel-totem/pull/337
Resolved here
