### ISSUE TITLE
Config file missing.

### ISSUE THREAD

**Issue by mgip** [codestudiollc/laravel-totem#336]
Any artisan command to publish totem.php config file?

Thanks

**Comment by qschmick** [comment]
You can run `php artisan vendor:publish` and choose any of the vendor assets to publish for your different composer dependencies. You can also run this explicit command to just publish the config files for Totem 
 `php artisan vendor:publish --tag=totem-config`

**Comment by mgip** [comment]
> You can run `php artisan vendor:publish` and choose any of the vendor assets to publish for your different composer dependencies. You can also run this explicit command to just publish the config files for Totem `php artisan vendor:publish --tag=totem-config`

I thought that it only works with specific packages, but you have taught me that it can work with any.

thanks so much @qschmick . I appreciate it
