### ISSUE TITLE
Migrations rollback bug?

### ISSUE THREAD

**Issue by thomark1** [codestudiollc/laravel-totem#368]
Hello,

I came across an error while rolling back the migrations. I enclose the screenshot:
![totem_migration_rollback](https://github.com/codestudiohq/laravel-totem/assets/37288204/29b22223-3df9-4c39-8283-495dc763f998)

LARAVEL VERSION: ^9.19
TOTEM VERSION: ^10.0
No table prefix set in configuration file.

**Comment by jonnott** [comment]
Fix PR'd

**Comment by jonnott** [comment]
@thomark1 You can close this issue now..
