### ISSUE TITLE
Laravel 11 support?

### ISSUE THREAD

**Issue by itcbilisim** [codestudiollc/laravel-totem#375]

**Comment by jonnott** [comment]
+1

**Comment by jonnott** [comment]
@qschmick Are you able to help?

**Comment by qschmick** [comment]
I currently don't have the time to help add this. @tomschlick do you have any bandwidth for this?

**Comment by jonnott** [comment]
> I currently don't have the time to help add this. @tomschlick do you have any bandwidth for this?

Made a PR @qschmick https://github.com/codestudiohq/laravel-totem/pull/381

**Comment by jonnott** [comment]
@itcbilisim New version 11.0 is out, you can close this issue now I think.

**Comment by itcbilisim** [comment]
@jonnott thank you very much. I am grateful for your support.

**Comment by itcbilisim** [comment]
finish

**Comment by jonnott** [comment]
> @jonnott thank you very much. I am grateful for your support.

Just doing my bit for OSS where I can!
