### ISSUE TITLE
Exception in view/edit task

### ISSUE THREAD

**Issue by olegmelnik** [codestudiollc/laravel-totem#44]
Happens when you open the task page

<img width="1277" alt="2017-10-07 15 02 07" src="https://user-images.githubusercontent.com/7072397/31307711-3123130a-ab72-11e7-983a-84a922a4d571.png">

**Comment by roshangautam** [comment]
I am not able to reproduce it. More information would be helpful to debug.

**Comment by roshangautam** [comment]
could this be related to #52 ?

**Comment by roshangautam** [comment]
This should be working fine in the latest release
