### ISSUE TITLE
[Question] Is there a way to clear the Totem task list from the command line?

### ISSUE THREAD

**Issue by alexstone** [codestudiollc/laravel-totem#45]
So I set up Totem on a project and when trying to create or edit tasks, it through errors. Eventually, my solution was to go in the database and truncate the Totem tables to get a fresh start.

However, when I run `artisan schedule:list`, I see the jobs that I had added that I need to remove. Since they are no longer listed in the web interface, I seem to have no way to clear them from the system.

How would I remove these jobs so they stop firing?

**Comment by roshangautam** [comment]
if you manually truncated your database you will have to run artisan cache:clear to clear existing cache.

**Comment by alexstone** [comment]
ayoooo! that did it, it seems. I should have tried that earlier
