### ISSUE TITLE
Can't Pass Single Command Parameter Without a Value

### ISSUE THREAD

**Issue by brycethornton** [codestudiollc/laravel-totem#48]
I have a command that takes a single parameter. Example:

`php artisan check-prices --only-simple`

This seems to cause a problem for Totem because when it eventually gets passed to `Artisan::call` it needs to be passed as a key/value array like this:

`["--only-simple" => true]`

Currently it seems to pass like this:

`["--only-simple"]`

This results in this error:

`The "1" argument does not exist.`

I see the code in `compileParameters` expects all parameters to have values (via the `explode` call [here](https://github.com/codestudiohq/laravel-totem/blob/30ce30901d21fecb9abdcdfa8acb9bfa25193a31/src/Task.php#L76)). Is there any reason not to allow parameters without values?

**Comment by roshangautam** [comment]
Thats definitely an edge case that I overlooked. If you have a solution, I would be more than happy to review and merge it. Thanks.

**Comment by qschmick** [comment]
@roshangautam Added a PR to fix this issue and also add some basic tests to the compileParamters method.

**Comment by roshangautam** [comment]
Thanks @qschmick . I will release a version momentarily.
