### ISSUE TITLE
Please rename the tables to totem_*

### ISSUE THREAD

**Issue by hailwood** [codestudiollc/laravel-totem#50]
This package is fairly specific but it has table names that are highly likely to conflict with an existing application's tables.

"tasks" for example, we have a `Task` model in about 60% of our applications and having to change the table to `application_tasks` because a package has already used that table name is frustrating. 

I am suggesting that we rename all tables to `totem_*`. We'll also need to drop and re-create the foreign key constraints as they'll still be named towards the old tables.

```php
// Drop foreign key constraints
// ...

Schema::rename('tasks', 'totem_tasks');
Schema::rename('task_frequencies', 'totem_task_frequencies');
Schema::rename('task_results', 'totem_task_results');
Schema::rename('frequency_parameters', 'totem_frequency_parameters');

//Recreate foreign key constraints
// ...
```

**Comment by roshangautam** [comment]
I probably want to implement this using a prefix configuration such that if its not necessary it will use the default table names but if necessary you can configure the prefix to avoid collision with your existing tables.
