### ISSUE TITLE
config/totem.php is missing

### ISSUE THREAD

**Issue by ftrotter** [codestudiollc/laravel-totem#64]
The readme implies that there is a file called config/totem.php

This file is not installed as a package asset during the installation process. 

Either the readme needs to reflect that the totem.php file needs to be copied manually or the 

`php artisan totem:assets
`
command should install the totem.php file (assuming there is not already a file)...

-FT

**Comment by hosquiat** [comment]
Was this ever resolved?

**Comment by roshangautam** [comment]
just released a new version for both 2.* and 3.*

You can now use vendor:publish to publish totem config
