### ISSUE TITLE
missing composer requirements for laravelcollective/html

### ISSUE THREAD

**Issue by ftrotter** [codestudiollc/laravel-totem#65]
Your basic view crashes unless 

composer require "laravelcollective/html":"^5.4.0"

has been added. It says that class Form is missing...

this should be added to your composer.json as a requirement...

-FT

**Comment by qschmick** [comment]
@ftrotter Thanks for the details, we'll take a look at this now.

**Comment by qschmick** [comment]
@ftrotter Just tagged v2.2.2 with the fix for this.
