### ISSUE TITLE
[REQUEST] Make database connection configurable

### ISSUE THREAD

**Issue by dejury** [codestudiollc/laravel-totem#73]
We want to store the cronjobs and their logs into a seperate database. Can you please add this to be configurable?

**Comment by liran-co** [comment]
+1

**Comment by gcdsm12** [comment]
+1 Please add logs to be configurable. It is very important for me.

**Comment by qschmick** [comment]
@dejury Sorry for the long wait, please see [PR 130](https://github.com/codestudiohq/laravel-totem/pull/130)
