### ISSUE TITLE
Command never gets to executes

### ISSUE THREAD

**Issue by qerim** [codestudiollc/laravel-totem#78]
Laravel: `5.5` (not fresh install),
Server: `Debian 8`, `Nginx 1.12` , `PHP 7.1`, `composer 1.6.3`
Totem Table Prefix:  `totem_`

I'm running the queue worked manually just for testing: `php artisan queue:work`

When creating a task in Totem, I notice the queue worker log outputting this continuously:

    [2018-02-21 12:22:19] Processing: Studio\Totem\Events\Creating
    [2018-02-21 12:22:19] Processing: Studio\Totem\Events\Created
    [2018-02-21 12:22:19] Processing: Studio\Totem\Events\Creating
    [2018-02-21 12:22:19] Processing: Studio\Totem\Events\Created
    [2018-02-21 12:22:19] Processing: Studio\Totem\Events\Creating
    ....
    ....

The job never executes even though I do have a cron running:

`* * * * * php /var/www/development.mydomain.co.uk/current/artisan schedule:run >> /dev/null 2>&1`

When I delete the task, the following exception shows in the `failed_jobs` table:

**payload**

    {
        "displayName": "Studio\\Totem\\Events\\Created",
        "job": "Illuminate\\Queue\\CallQueuedHandler@call",
        "maxTries": null,
        "timeout": null,
        "timeoutAt": null,
        "data":
        {
            "commandName": "Illuminate\\Broadcasting\\BroadcastEvent",
            "command": "O:38:\"Illuminate\\Broadcasting\\BroadcastEvent\":7:{s:5:\"event\";O:27:\"Studio\\Totem\\Events\\Created\":2:{s:4:\"task\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":3:{s:5:\"class\";s:17:\"Studio\\Totem\\Task\";s:2:\"id\";i:13;s:10:\"connection\";s:11:\"development\";}s:6:\"socket\";N;}s:10:\"connection\";N;s:5:\"queue\";N;s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:7:\"chained\";a:0:{}}"
        }
    }

**exception**

    Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [Studio\Totem\Task]. in /var/www/development.mydomain.co.uk/releases/24/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:412
    Stack trace:
    #0 /var/www/development.mydomain.co.uk/releases/24/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(54): Illuminate\Database\Eloquent\Builder->firstOrFail()
    #1 /var/www/development.mydomain.co.uk/releases/24/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(41): Studio\Totem\Events\Event->getRestoredPropertyValue(Object(Illuminate\Contracts\Database\ModelIdentifier))
    #2 [internal function]: Studio\Totem\Events\Event->__wakeup()
    #3 /var/www/development.mydomain.co.uk/releases/24/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(42): unserialize('O:38:"Illuminat...')
    #4 /var/www/development.mydomain.co.uk/releases/24/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
    #5 /var/www/development.mydomain.co.uk/releases/24/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()
    #6 /var/www/development.mydomain.co.uk/releases/24/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
    #7 /var/www/development.mydomain.co.uk/releases/24/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
    #8 /var/www/development.mydomain.co.uk/releases/24/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
    #9 /var/www/development.mydomain.co.uk/releases/24/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
    #10 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
    #11 /var/www/development.mydomain.co.uk/releases/24/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
    #12 /var/www/development.mydomain.co.uk/releases/24/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
    #13 /var/www/development.mydomain.co.uk/releases/24/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
    #14 /var/www/development.mydomain.co.uk/releases/24/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
    #15 /var/www/development.mydomain.co.uk/releases/24/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
    #16 /var/www/development.mydomain.co.uk/releases/24/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
    #17 /var/www/development.mydomain.co.uk/releases/24/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
    #18 /var/www/development.mydomain.co.uk/releases/24/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #19 /var/www/development.mydomain.co.uk/releases/24/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #20 /var/www/development.mydomain.co.uk/releases/24/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #21 /var/www/development.mydomain.co.uk/releases/24/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #22 /var/www/development.mydomain.co.uk/releases/24/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #23 /var/www/development.mydomain.co.uk/releases/24/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #24 {main}

**Comment by qerim** [comment]
Strange issue. `BROADCAST_DRIVER` was set to `redis`. Chnaged that to `null`. This fixed the infinite loop issue.

When running `php artisan schedule:list`, totem tasks were not showing. Add the `ConsoleServiceProvider` to app.php and everything is fine now.


config/broadcast.php
`'default' => env('BROADCAST_DRIVER', 'null'),`

**config/app.php**
`Studio\Totem\Providers\ConsoleServiceProvider::class,`

**Comment by LeandroVCastro** [comment]
> Strange issue. `BROADCAST_DRIVER` was set to `redis`. Chnaged that to `null`. This fixed the infinite loop issue.
> 
> When running `php artisan schedule:list`, totem tasks were not showing. Add the `ConsoleServiceProvider` to app.php and everything is fine now.
> 
> config/broadcast.php
> `'default' => env('BROADCAST_DRIVER', 'null'),`
> 
> **config/app.php**
> `Studio\Totem\Providers\ConsoleServiceProvider::class,`

This solved my problem. Thanks.

**Comment by sxc654** [comment]
> Strange issue. `BROADCAST_DRIVER` was set to `redis`. Chnaged that to `null`. This fixed the infinite loop issue.
> 
> When running `php artisan schedule:list`, totem tasks were not showing. Add the `ConsoleServiceProvider` to app.php and everything is fine now.
> 
> config/broadcast.php `'default' => env('BROADCAST_DRIVER', 'null'),`
> 
> **config/app.php** `Studio\Totem\Providers\ConsoleServiceProvider::class,`

Thanks.
