### ISSUE TITLE
Undefined variable: errors

### ISSUE THREAD

**Issue by raakkan** [codestudiollc/laravel-totem#94]
Undefined variable: errors (View: D:\web projects\marketing\server\vendor\studio\laravel-totem\resources\views\tasks\index.blade.php)

please help how to solve this problem

**Comment by qschmick** [comment]
@TechShankar What version of Totem are you running? Which version of PHP? Which version of Laravel?

**Comment by raakkan** [comment]
totem 3.2, laravel 5.6, php 7

**Comment by qschmick** [comment]
If you set `APP_DEBUG=true` can you provide any details on which var is undefined?

**Comment by raakkan** [comment]
yes i'm set app_debug=true see this error

![screenshot 3](https://user-images.githubusercontent.com/26565082/37972653-6cabeb4e-31f6-11e8-8013-edb93d0ccf79.png)

**Comment by qschmick** [comment]
Your web middleware is missing an item, if you update the file located at `app/Http/Kernel.php` and make sure it has the `\Illuminate\View\Middleware\ShareErrorsFromSession::class,` for the web middleware. If you have overridden the totem middleware with something other then web, make sure that middleware group has that class included.

https://github.com/laravel/laravel/blob/master/app/Http/Kernel.php

```
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
+            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
```

**Comment by raakkan** [comment]
uncommented this class \Illuminate\View\Middleware\ShareErrorsFromSession::class, in app/Http/Kernel.php
now not working my whole project.

![screenshot 4](https://user-images.githubusercontent.com/26565082/37973656-a00b6dbe-31f8-11e8-81fe-143e354b2672.png)

**Comment by raakkan** [comment]
above problem fixed.
http://127.0.0.1:8000/totem this url not working. see this image.
![screenshot 5](https://user-images.githubusercontent.com/26565082/37974514-bcba5f9a-31fa-11e8-9503-9e2e5b122246.png)

**Comment by roshangautam** [comment]
This is not related to Totem. Its possibly a problem on your end. I can verify that Totem works fine with a fresh installation of Laravel.
