### ISSUE TITLE
Error when deleteing task

### ISSUE THREAD

**Issue by qerim** [codestudiollc/laravel-totem#95]
Laravel: `5.6` (fresh install),
Server: `Debian 8`, `Nginx 1.12` , `PHP 7.1`, `composer 1.6.3`
Totem Table Prefix:  `totem_`
Queue Driver: `redis`
Queue Monitor: `Laravel Horizon`

Task creating, executing is all working well, however when deleting a Task, it disappears from Totem dashboard, but the `Deleted` item in the Queue fails.

![image](https://user-images.githubusercontent.com/3625009/38618210-d49cd2f4-3d90-11e8-8a10-453c5648f3c2.png)

Full error log:

    Studio\Totem\Events\Deleted
    ID: 76535
    Queue: {development}
    Tags: Studio\Totem\Task:66
    Failed At: 18-04-11 13:54:02

    Error
    Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [Studio\Totem\Task]. in /var/www/public/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:416
    Stack trace:
    #0 /var/www/public/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(85): Illuminate\Database\Eloquent\Builder->firstOrFail()
    #1 /var/www/public/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(55): Studio\Totem\Events\Event->restoreModel(Object(Illuminate\Contracts\Database\ModelIdentifier))
    #2 /var/www/public/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(45): Studio\Totem\Events\Event->getRestoredPropertyValue(Object(Illuminate\Contracts\Database\ModelIdentifier))
    #3 [internal function]: Studio\Totem\Events\Event->__wakeup()
    #4 /var/www/public/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(42): unserialize('O:38:"Illuminat...')
    #5 /var/www/public/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
    #6 /var/www/public/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(322): Illuminate\Queue\Jobs\Job->fire()
    #7 /var/www/public/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(272): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
    #8 /var/www/public/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
    #9 /var/www/public/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', '{development}', Object(Illuminate\Queue\WorkerOptions))
    #10 /var/www/public/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', '{development}')
    #11 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
    #12 /var/www/public/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
    #13 /var/www/public/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
    #14 /var/www/public/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
    #15 /var/www/public/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
    #16 /var/www/public/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
    #17 /var/www/public/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
    #18 /var/www/public/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
    #19 /var/www/public/vendor/symfony/console/Application.php(865): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #20 /var/www/public/vendor/symfony/console/Application.php(241): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #21 /var/www/public/vendor/symfony/console/Application.php(143): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #22 /var/www/public/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #23 /var/www/public/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #24 /var/www/public/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #25 {main}

The deleted task continues to try and execute because it doesn't recognised that it's been deleted.

![image](https://user-images.githubusercontent.com/3625009/38618675-448e28d2-3d92-11e8-9aa2-64497ede8346.png)

Same error log as above.

**Comment by danieluyo** [comment]
Got to https://github.com/laravel/horizon for horizon
