### ISSUE TITLE
Import throws sql error when importing frequencies

### ISSUE THREAD

**Issue by nhp** [codestudiollc/laravel-totem#96]
Reproduce: Create a task with a frequency, export it (json looks good), import it. 

Following error occurs: ```An error occurred while importing data.SQLSTATE[HY000]: General error: 1364 Field 'task_id' doesn't have a default value (SQL: insert into `task_frequencies` (`label`, `interval`, `updated_at`, `created_at`) values (Every Ten Minutes, everyTenMinutes, 2018-05-03 11:29:30, 2018-05-03 11:29:30))```

I would assume it should work, but it looks like the createOrUpdate is not working as expected for creating new ones.

[totem_tasks.json.gz](https://github.com/codestudiohq/laravel-totem/files/1970292/totem_tasks.json.gz)

**Comment by roshangautam** [comment]
This should be working fine in the latest release. I tested it with the json file attached in the issue.
