### ISSUE TITLE
Import Form has different action than used route

### ISSUE THREAD

**Issue by nhp** [codestudiollc/laravel-totem#97]
According to ```artisan route:list``` the allowed methods for ```task/import``` are GET and HEAD but the form uses POST. Is there reasoning for this? If so please let me know otherwise i will bring up a PR for this later.

**Comment by thindery** [comment]
I'm interested in this too. Throws an error `MethodNotAllowedHttpException` on upload.

**Comment by roshangautam** [comment]
This is now fixed in the latest release.
