### ISSUE TITLE
[Request] Option to run a task once

### ISSUE THREAD

**Issue by syphernl** [codestudiollc/laravel-totem#98]
It would be nice if one-off tasks could be be added as well. 

Right now with the correct expression you can target it to run at a specific date/time but it would then run again the year after, unless the task has been removed.

**Comment by roshangautam** [comment]
I don't think its possible as totem is based on Laravel scheduler and Laravel's scheduler uses cron to run the schedule. Cron scheduling do not allow you to schedule one off tasks. There's  a different linux utility called `at` which does that.
