### ISSUE TITLE
Totem not running task. But running Kernel Tasks.

### ISSUE THREAD

**Issue by idealb** [codestudiollc/laravel-totem#99]
My tasks run when I execute them directly on the the dashboard but on when they are scheduled. But the scheduled command on Kernel they are running instead. 

I am running php 7.2
Laravel 5.6.*
Totem 3.2

**Comment by roshangautam** [comment]
Please make sure you have configured Laravel scheduler properly and followed totem's documentation. Feel free to open another issue if you are still having problems. Try to provide more details or errors you are encountering.

**Comment by idealb** [comment]
I am not encountering any issue. They are just not running. When I press run on the run icon on totem admin they work. But they do not work automatically.

**Comment by roshangautam** [comment]
Have you tried configuring your schedule as documented here :
https://laravel.com/docs/5.6/scheduling

**Comment by idealb** [comment]
I have scheduled Crons running on my Kernel. Only totem scheduled Crons are not running.
